/* GENERATED FILE - do not edit by hand.
   Source: artist-pages-data.json   Build: python tools/build_songs_data.py */
window.SONG_DATA = {
  names: {
    "andadar carav": "Անդադար ծարավ",
    "Astghayin_Shghta_A": "Աստղային շղթա",
    "The Sun Cries Too(Արևն էլ է լաց լինում)": "Արևն էլ է լացում (անգլ)",
    "Vahan_Teryan_Gisher": "Գիշեր (Վ.Տ)",
    "B_Es_im_anush_Hayastani": "Ես իմ անուշ Հայաստանի",
    "ergi chapov": "Երգի Չափով",
    "El_ban_chunem_Remix": "Էլ բան չունեմ",
    "taxicy vat margare e": "Թախիծը վատ մարգարե է",
    "Իմ Գեղեցկուհի ընկերուհիները": "Իմ Գեղեցկուհի ընկերուհիները",
    "Իմ Գեղեցկուհի ընկերուհիները twist rock & roil": "Իմ Գեղեցկուհի ընկերուհիները (Twist Rock & Roll)",
    "Իմ Գեղեցկուհի ընկերուհիներըroc&roil": "Իմ Գեղեցկուհի ընկերուհիները (Rock & Roll)",
    "im ser": "Իմ սեր",
    "inchi-hamar": "Ինչի համար",
    "inch_e_koracy_qarcr": "Ինչո՞ւ է կորածն այսքան քաղցրանում",
    "lur-heraxos": "Լուռ հեռախոս",
    "lur uji simfonia": "Լուռ ուժի սիմֆոնիան",
    "luse arzaganq": "Լուսե արձագանք",
    "Luse_Hekiat_A": "Լուսե հեքիաթ",
    "Lrutyan_unker": "Լռության ընկեր",
    "Lsir_vordis": "Լսիր որդիս",
    "Կատակ յարի երգ պար 4 լեզվով": "Կատակ յարի երգ պար 4 լեզվով",
    "Katak_Yari_Ergu": "Կատակ յարի երգը",
    "Կատակ Յարի Երգը": "Կատակ Յարի Երգը",
    "Katak_Yari_Ergu rem": "Կատակ յարի երգը 2",
    "haverji-erty": "Հավերժի երգը",
    "hogu-arzaganq": "Հոգու արձագանք",
    "Մեղքի եզրին": "Մեղքի եզրին",
    "On the Edge of Sin": "On the Edge of Sin",
    "Meghki_ezrin_Remix": "Между страстью и грехом",
    "Նախանձում եմ": "Նախանձում եմ",
    "shshnjatc": "Շշնջաց",
    "shshnjatc-noric": "Շշնջաց նորից",
    "shepot": "Шёпот",
    "Ջրահարսեր Ремикс Ремикс_2": "Ջրահարսեր Ռեմիքս 2",
    "Ջրահարսեր Ремикс Ремикс_3": "Ջրահարսեր Ռեմիքս 3",
    "ser-anurji": "Սեր անուրջի",
    "sirelis": "Սիրելիս",
    "siro-kenacy": "Սիրո կենաց",
    "Поцелуй_ветра": "Քամու համբույրից (Հ.Ս)",
    "Vahan_Teryan_MEGhAVOR_AChKERU": "Քո մեղավոր աչքերը (Վ.Տ)",
    "qo-jinj-hogin": "Քո ջինջ հոգին",
    "A Song Away": "A Song Away",
    "IM JEALOUS OF THE MOSQUITO": "IM JEALOUS OF THE MOSQUITO",
    "Our Lovely Mermaids": "Our Lovely Mermaids",
    "Roses in a Sieve": "Roses In A Sieve",
    "The Eternal Thirst": "The Eternal Thirst",
    "На расстоянии песни": "На расстоянии песни",
    "Песня шутка": "Песня шутка",
    "pastayannaya jajda": "Постоянная жажда",
    "Ревую к комару": "Ревную к комару",
    "Эй наши русалки": "Эй наши русалки",
    "Ρόδα στο Κόσκινο": "Ρόδα στο Κόσκινο",
    "ვარდები საცერში": "ვარდები საცერში",
    "ჩვენი ქალთევზებო": "ჩვენი ქალთევზებო",
    "Akh_inch_anem_sirud_het": "Ախ ինչ անեմ սիրուդ հետ",
    "agh & dagy": "Աղն ու դաղը",
    "Andzrevum_e": "Անձրևում է",
    "Mtnets_arants_kez_Duet": "Առանց քեզ մթնեց",
    "ari-khmenq": "ԱՐԻ ԽՄԵՆՔ · ДАВАЙ ВЫПЬЕМ · BUVONS",
    "Ari_klini": "Արի կլինի",
    "Aryev_darnam": "Արև դառնամ",
    "byur harvacneric": "Բյուր հարվածներից",
    "bjur u bjur angam": "Բյուր ու բյուր անգամ",
    "Galis_e_mi_pah_003": "Գալիս է մի պահ",
    "Garun_er_003": "Գարուն է",
    "Garun e bajc zun e arel": "Գարուն է բայց ձյուն է արել",
    "gereckuhi": "Գեղեցկուհի",
    "gjuk lusiny": "Գժուկ լուսին",
    "gij": "Գիժ",
    "gij-qamin": "Գիժ քամի",
    "Gisher_e_004": "Գիշեր է",
    "Gisherits_depi_luys_Silva_Gulanyan_005": "Գիշերից լույս",
    "gitem el inz ches spasum": "Գիտեմ էլ ինձ չես սպասում",
    "Gitem_hogis_A": "Գիտեմ հոգիս",
    "Gitem_ches_galu_B": "Գիտեմ չես գալու",
    "gortrik-ankun": "Գողտրիկ անկյուն",
    "Դավաճան հայ": "Դավաճան հայ",
    "der-inz-voch-mek-chi-sirel-qo-pes": "Դեռ ինձ ոչ մեկ չի սիրել քո պես",
    "Դու իմ աշխարհն ես": "Դու իմ աշխարհն ես",
    "Dran_Takotsu_003": "Դռան թակոց",
    "ete asem": "Եթե ասեմ",
    "Եղբայր իմ անգին": "Եղբայր իմ անգին",
    "Es_irakan_em_004": "Ես իրական եմ",
    "Es_sirum_em_ko_zhpitu_B": "Ես սիրում եմ քո ժպիտը",
    "Es_kez_sirum_em": "Ես քեզ սիրում եմ",
    "Erazankneri_aytsu_Part_Gisherva_002": "Երազանքների այց գիշերվա",
    "erazi kyanq": "Երազի կայանք",
    "erazi kyamq roc": "Երազի կայանք (ռոք)",
    "Երանի գայիր(Just Like Before)": "Երանի գայիր (Just Like Before)",
    "Erb_verkers_hanger_dardzri_Lyrics_by_Silva_Gulanyan_003": "Երբ երգերս հանգեր դարձան",
    "ergichy-dari": "Երգիչի դարի",
    "Erku_khent_hogi_Duet_Silva_Gulanyan_004": "Երկու խենթ հոգի",
    "Թախծիս անունը": "Թախծիս անունը",
    "Թախծիս անունը_1": "Թախծիս անունը (Տանգո)",
    "Թանկ հուշը": "Թանկ հուշը",
    "te karotum es": "Թե կարոտում ես",
    "jpta hogis": "Ժպտա հոգիս",
    "Im_erazats_ashkharu_003": "Իմ երազած աշխարհում",
    "im-tsovagur": "Իմ ծովագյուղ",
    "Իմ Քնքուշ Սևան": "Իմ Քնքուշ Սևան",
    "inch-em-anelu": "Ինչ եմ անելու",
    "inchu_es_ayskan_indz_otar_dardzel_004": "Ինչու ես այսքան ինձ օտար դարձել",
    "lok cav u dard": "Լոկ ցավ ու դարդ",
    "luse hrashq": "Լուսե հրաշք",
    "lrutian tchich": "Լռության ճիչ",
    "xararutun ber": "Խաղաղություն բեր",
    "xerdvac karot": "Խեղդված կարոտ",
    "xerdvac karot patasxan": "Խեղդված կարոտ պատասխան",
    "խենթ խաղեր": "խենթ խաղեր",
    "xent siro qamin": "Խենթ սիրո քամին",
    "xentern u lusiny": "Խենթերն ու լուսինը",
    "խենթի նման սիրահարվեցի": "խենթի նման սիրահարվեցի",
    "xind manuk": "Խինդ մանուկ",
    "xortakvor nav": "Խորտակվող նավ",
    "tsov-arev-achqer": "Ծով արև աչքեր",
    "Ծովի մեջ աչքերդ": "Ծովի մեջ աչքերդ",
    "Mer_Srterum_kanchu_004": "Կանչ մեր սրտերում",
    "Կարոտի խենթի": "Կարոտի խենթի",
    "karotiali shurterin": "Կարոտիալի շուրթերին",
    "kgam_sirelis": "Կգամ սիրելիս",
    "Kenatsd_khmem_B_Brinderò_per_Te": "Կենացդ խմեմ",
    "Kuratsats_achkin_luysu_003": "Կուրացած աչքի լույս",
    "Hay_aragil": "Հայ արագիլ",
    "Hayots_ashkarh_A": "Հայոց աշխարհ",
    "Havat_em_vozum_003": "Հավատ եմ ուզում",
    "HERO_MOTIK_UNKERNERIS_003": "Հեռու մոտիկ ընկերներիս",
    "Hetd_inch_e_katarvum": "Հետդ ինչ է կատարվում",
    "RokHetd_Inch_E_Katarvum_003": "Հետդ ինչ է կատարվում",
    "hiastapvac": "Հիասթափված",
    "hima": "Հիմա",
    "hogu giny": "Հողի գինը",
    "Kyanku_Hrashk_e_005": "Հրաշք կյանք",
    "Dzig_tarineri_luys_003": "Ձիգ տարիների լույս",
    "Tchaxr e pargevum ": "Ճախր է պարգևում",
    "Chisht_zhamanakin_At_The_Right_Time": "Ճիշտ ժամանակին",
    "mek tari el ancav": "Մեկ տարի էլ անցավ",
    "mern zepur": "Մեղմ զեփյուռը",
    "Title_Mi_tanjir_hogis_Multilingual_Emotional_Duet_Lyrics_by_Silva_Gulanyan_002": "Մի տանջիր հոգիս բազմալեզու",
    "Resta_nei_nostri_cuori": "Մնա մեր սրտերում",
    "Nerir sirelis": "Ներիր սիրելիս",
    "nerqnapanak": "Ներքնապանակ",
    "Nrboren_Garnunk_003": "Նրբորեն գարունք",
    "ov em qez hamar": "Ո՞վ եմ քեզ համար",
    "ughernery-lac-chen-linum": "Ուժեղներն էլ լաց են լինում",
    "Che_chem_toghni_B": "Չե չեմ թողնի",
    "chem moracel": "Չեմ մոռացել",
    "Ches_moranalu_003": "Չես մոռանալու",
    "Jaheli_nman_003": "Ջահելի նման",
    "Tiezerk_Jinj_Lazur": "Ջինջ տիեզերք",
    "ser da ardioq": "Սեր է դա արդիոք",
    "ser eir xarum": "Սեր էիր խաղում",
    "Սիրել հենց հոգուն": "Սիրել հենց հոգուն",
    "Սիրել հենց հոգուն (1)": "Սիրել հենց հոգուն (1)",
    "Sirir_indz_hogis_FRAM_Duet": "Սիրիր ինձ հոգիս",
    "melodia lubvi": "Սիրո երաժշտություն",
    "siro cnundy": "Սիրո ծնունդ",
    "S_irum_em_kez_I_love_you": "Սիրում եմ քեզ",
    "sirty xentacav": "Սիրտս խենթացավ",
    "Srteri_kanchu_003": "Սրտերի կանչ",
    "Ka_mi_ashkharh_vor_srtov_e_karutsvats": "Սրտով կառուցված աշխարհ",
    "Tesilk_Silva_Gulanyan_Remix_Remix": "Տեսիլք",
    "Տիեզերական կինը": "Տիեզերական կինը",
    "Տիեզերական կինը (Remastered)": "Տիեզերական կինը (Remastered)",
    "Տիեզերական կինը roc": "Տիեզերական կինը (ռոք)",
    "cav anbujeli": "Ցավ անբուժելի",
    "AKhor_vo_tsavits_tsnvats": "Ցավից ծնված",
    "Curt xavaric": "Ցուրտ խավարից",
    "Քեզ դուրս եմ արել": "Քեզ դուրս եմ արել",
    "Kez_khenti_nman_siraharvetsi_Duet_Tango": "Քեզ խենթի նման սիրահարվեցի (Duet Tango)",
    "qez karotelis": "Քեզ կարոտելիս",
    "Քեզ կարոտելիս": "Քեզ կարոտելիս",
    "qo cov achqeri kajcern em sirum": "Քո աչքերի կայծն եմ սիրում",
    "qo_drakhtum_002": "Քո դրախտում",
    "Քո ժպիտները հավաքեմ": "Քո ժպիտները հավաքեմ",
    "Ko_koghkin_vorish_em_003": "Քո կողքին ուրիշ եմ",
    "Ko_hmayki_gerin": "Քո հմայքի գերին",
    "Kuyr_eghbayr_003": "Քույր եղբայր",
    "ov e kimy": "Օվ է կինը",
    "frants_Harbel_em_vozum": "Ֆրանսերեն հարբել եմ ուզում",
    "Crazy Breeze of Love": "Crazy Breeze of Love",
    "I Gave My Sorrow The Name": "I Gave My Sorrow The Name",
    "Longing for You": "Longing for You",
    "Love Unseen": "Love Unseen",
    "Love Unseen (1)": "Love Unseen (1)",
    "My Bright Dream": "My Bright Dream",
    "My Bright Dream (1)": "My Bright Dream (1)",
    "My Endless Dream": "My Endless Dream",
    "My Only Light": "My Only Light",
    "My Precious Love": "My Precious Love",
    "My Precious Love драгоценная любовь": "My Precious Love драгоценная любовь",
    "Never a Stranger": "Never a Stranger",
    "Powerless Against Memories": "Powerless Against Memories",
    "The Illusion of Longing": "The Illusion of Longing",
    "The Night's Embrace": "The Night's Embrace",
    "The Song of the Spring Breeze": "The Song of the Spring Breeze",
    "The Sun Cries Too": "The Sun Cries Too",
    "The Woman as the Universe": "The Woman as the Universe",
    "You Are My World": "You Are My World",
    "Безумный Ветер Любви": "Безумный Ветер Любви",
    "Любить лишь душу": "Любить лишь душу",
    "Любить лишь душу (1)": "Любить лишь душу (1)",
    "Мой светлый луч": "Мой светлый луч",
    "Образы тоски": "Образы тоски",
    "Перед памятью злой": "Перед памятью злой",
    "Светлый полёт": "Светлый полёт",
    "Сокровенный причал": "Сокровенный причал",
    "Тоска по мне": "Тоска по мне",
    "Тоскуя по тебе": "Тоскуя по тебе",
    "ti moy kislarod": "Ты мой кислород",
    "Ты мой мир": "Ты мой мир",
    "ti pridyosh komne": "Ты придёшь ко мне",
    "Я назвал свою печаль тоской": "Я назвал свою печаль тоской",
    "Խղճում եմ նրանց": "Խղճում եմ նրանց",
    "Ուզում եմ նորից մանկանալ": "Ուզում եմ նորից մանկանալ",
    "Ոսկե աշուն": "Ոսկե աշուն",
    "Աշնան Վալսը Պուրակում": "Աշնան Վալսը Պուրակում",
    "Ես չգիտեմ քե՞զ եմ սիրում": "Ես չգիտեմ քե՞զ եմ սիրում",
    "ajs xarum mian ujern e haxtum": "Այս խաղում ուժեղն է հաղթում",
    "Anund_Kin_e_004": "Անունդ կին է",
    "Անունդ կին է ֆրի տանգո": "Անունդ կին է (տանգո)",
    "Arajin_hambuyru": "Առաջին համբույր",
    "Arevamutits_araj": "Արևամուտից առաջ",
    "Bari_gisher": "Բարի գիշեր",
    "duet_Спокойной_ночи_Remix_Remix": "Բարի գիշեր (դուետ ռուս)",
    "spakojnoj nochi (kin)": "Բարի գիշեր (ռուս)",
    "Ginin_prprel_e": "Գինին փրփրել է",
    "gisherajin": "Գիշերային",
    "darnaham-ginin": "Դառնահամ գինի",
    "daravor karnin": "Դարավոր կաղնի",
    "Դու եկար": "Դու եկար",
    "Title_Es_arajva_pes_kez_karotum_em_Swiss_Pop_Ballad_Lyrics_by_Go_Hara_Remix_008": "Ես առաջվա պես քեզ կարոտում եմ",
    "Եվ ինչ է սերը": "Եվ ինչ է սերը",
    "Իմ հայելի": "Իմ հայելի",
    "Im_poezian": "Իմ պոեզիան",
    "la-fracise": "Լա Ֆրանս",
    "pered rasvetom": "Լուսաբացից առաջ",
    "kanchir-kgam": "Կանչիր կգամ",
    "Հայաստան, մեր սուրբ տուն": "Հայաստան, մեր սուրբ տուն",
    "HANDIPOMNERI_AYS_KhAChMEROKOM": "Հանդիպումների այս խաչմերուկում",
    "Hervits_Grkum em": "Հերվից գրկում եմ (Remix)",
    "hognel em ujer kin lineluc": "Հոգնել եմ ուժեղ կին լինելուց",
    "Hravirir_indz_parelu_tangon": "Հրավիրիր ինձ պարելու տանգո",
    "menq linelu enq": "Մենք լինելու ենք",
    "MI_TOGh_INDz_MENAK": "Մի թող ինձ մենակ",
    "Mi_siro_patmutyun": "Մի սիրո պատմություն",
    "urenineri lacor purakum": "Ուռենիների լացող պուրակում",
    "Չնոտագրված լռություն": "Չնոտագրված լռություն",
    "POETIS": "Պոետիս",
    "Սիրելով գնամ": "Սիրելով գնամ",
    "Sirogisher_Go_Hara": "Սիրո գիշեր",
    "cncir-users": "Ցնցիր ուսերս",
    "Փխրուն Լաց": "Փխրուն Լաց",
    "fracuzhenka": "Ֆրանսուհին",
    "Armenia, Our Sacred Home": "Armenia, Our Sacred Home",
    "Fragile Cry Has Risen Like": "Fragile Cry Has Risen Like",
    "Ill Leave Still Loving You": "I'll Leave Still Loving You",
    "I'm tired of being strong": "I'M Tired Of Being Strong",
    "My Mirror True": "My Mirror True",
    "You Came": "You Came",
    "Армения, наш святой дом": "Армения, наш святой дом",
    "Во мне поднялся хрупкий плач": "Во мне поднялся хрупкий плач",
    "Зеркало моё": "Зеркало моё",
    "Ты пришёл": "Ты пришёл",
    "устала быть сильной": "устала быть сильной",
    "Я уйду любя": "Я уйду любя",
    "Սոնետ 1": "Սոնետ 1",
    "Սոնետ 2": "Սոնետ 2",
    "Սոնետ 3": "Սոնետ 3",
    "Սոնետ 4": "Սոնետ 4",
    "Սոնետ 5": "Սոնետ 5",
    "Սոնետ 6": "Սոնետ 6",
    "Սոնետ 7": "Սոնետ 7",
    "Սոնետ 8": "Սոնետ 8",
    "Սոնետ 9": "Սոնետ 9",
    "Սոնետ 10": "Սոնետ 10",
    "Սոնետ 11": "Սոնետ 11",
    "Սոնետ 12": "Սոնետ 12",
    "Սոնետ  13": "Սոնետ 13",
    "Սոնետ  14": "Սոնետ 14",
    "Սոնետ  15": "Սոնետ 15",
    "Սոնետ  16": "Սոնետ 16",
    "Սոնետ  17": "Սոնետ 17",
    "Սոնետ  18": "Սոնետ 18",
    "Սոնետ  19": "Սոնետ 19",
    "Սոնետ  20": "Սոնետ 20",
    "Սոնետ  21": "Սոնետ 21",
    "Սոնետ  22": "Սոնետ 22",
    "Սոնետ  23": "Սոնետ 23",
    "Սոնետ  24": "Սոնետ 24",
    "Սոնետ  25": "Սոնետ 25",
    "Սոնետ  26": "Սոնետ 26",
    "Սոնետ  27": "Սոնետ 27",
    "Սոնետ  28": "Սոնետ 28",
    "Սոնետ  29": "Սոնետ 29",
    "Սոնետ  30": "Սոնետ 30",
    "Սոնետ  31": "Սոնետ 31",
    "Սոնետ  32": "Սոնետ 32",
    "Սոնետ  33": "Սոնետ 33",
    "Սոնետ  34": "Սոնետ 34",
    "Սոնետ  35": "Սոնետ 35",
    "Սոնետ  36": "Սոնետ 36",
    "Սոնետ  37": "Սոնետ 37",
    "Սոնետ  38": "Սոնետ 38",
    "Սոնետ  39": "Սոնետ 39",
    "Սոնետ  40": "Սոնետ 40",
    "Սոնետ  41": "Սոնետ 41",
    "Սոնետ  42": "Սոնետ 42",
    "Սոնետ  43": "Սոնետ 43",
    "Սոնետ  44": "Սոնետ 44",
    "Սոնետ  45": "Սոնետ 45",
    "Սոնետ  46": "Սոնետ 46",
    "Սոնետ  47": "Սոնետ 47",
    "Սոնետ  48": "Սոնետ 48",
    "Սոնետ  49": "Սոնետ 49",
    "Սոնետ  50": "Սոնետ 50",
    "Սոնետ  51": "Սոնետ 51",
    "Սոնետ  52": "Սոնետ 52",
    "Սոնետ  53": "Սոնետ 53",
    "Սոնետ  54": "Սոնետ 54",
    "Սոնետ  55": "Սոնետ 55",
    "Սոնետ  56": "Սոնետ 56",
    "Սոնետ  57": "Սոնետ 57",
    "Սոնետ  58": "Սոնետ 58",
    "Սոնետ  59": "Սոնետ 59",
    "Սոնետ  60": "Սոնետ 60",
    "Սոնետ  61": "Սոնետ 61",
    "Սոնետ  62": "Սոնետ 62",
    "Սոնետ  63": "Սոնետ 63",
    "Սոնետ  64": "Սոնետ 64",
    "Սոնետ  65": "Սոնետ 65",
    "Սոնետ  66": "Սոնետ 66",
    "Սոնետ  67": "Սոնետ 67",
    "Սոնետ  68": "Սոնետ 68",
    "Սոնետ  69": "Սոնետ 69",
    "Սոնետ  70": "Սոնետ 70",
    "Սոնետ  71": "Սոնետ 71",
    "Սոնետ  72": "Սոնետ 72",
    "Սոնետ  73": "Սոնետ 73",
    "Սոնետ  74": "Սոնետ 74",
    "Սոնետ  75": "Սոնետ 75",
    "Սոնետ  76": "Սոնետ 76",
    "Սոնետ  77": "Սոնետ 77",
    "Սոնետ  78": "Սոնետ 78",
    "Սոնետ  79": "Սոնետ 79",
    "Սոնետ  80": "Սոնետ 80",
    "Սոնետ  81": "Սոնետ 81",
    "Սոնետ  82": "Սոնետ 82",
    "Սոնետ  83": "Սոնետ 83",
    "Սոնետ  84": "Սոնետ 84",
    "Սոնետ  85": "Սոնետ 85",
    "Սոնետ  86": "Սոնետ 86",
    "Սոնետ  87": "Սոնետ 87",
    "Սոնետ  88": "Սոնետ 88",
    "Սոնետ  89": "Սոնետ 89",
    "Սոնետ  90": "Սոնետ 90",
    "Սոնետ  91": "Սոնետ 91",
    "Սոնետ  92": "Սոնետ 92",
    "Սոնետ  93": "Սոնետ 93",
    "Սոնետ 94": "Սոնետ 94",
    "Սոնետ  95": "Սոնետ 95",
    "Սոնետ  96": "Սոնետ 96",
    "Սոնետ  97": "Սոնետ 97",
    "Սոնետ  98": "Սոնետ 98",
    "Սոնետ  99": "Սոնետ 99",
    "Սոնետ  100": "Սոնետ 100",
    "Սոնետ  101": "Սոնետ 101",
    "Սոնետ  102": "Սոնետ 102",
    "Սոնետ  103": "Սոնետ 103",
    "Սոնետ  104": "Սոնետ 104",
    "Սոնետ  105": "Սոնետ 105",
    "Սոնետ  106": "Սոնետ 106",
    "Սոնետ  107": "Սոնետ 107",
    "Սոնետ  108": "Սոնետ 108",
    "Սոնետ  109": "Սոնետ 109",
    "Սոնետ  110": "Սոնետ 110",
    "Սոնետ  111": "Սոնետ 111",
    "Սոնետ  112": "Սոնետ 112",
    "Սոնետ  113": "Սոնետ 113",
    "Սոնետ  114": "Սոնետ 114",
    "Սոնետ  115": "Սոնետ 115",
    "Սոնետ  116": "Սոնետ 116",
    "Սոնետ  117": "Սոնետ 117",
    "Սոնետ  118": "Սոնետ 118",
    "Սոնետ  119": "Սոնետ 119",
    "Սոնետ  120": "Սոնետ 120",
    "Սոնետ  121": "Սոնետ 121",
    "Սոնետ  122": "Սոնետ 122",
    "Սոնետ  123": "Սոնետ 123",
    "Սոնետ  124": "Սոնետ 124",
    "Սոնետ  125": "Սոնետ 125",
    "Սոնետ  126": "Սոնետ 126",
    "Սոնետ  127": "Սոնետ 127",
    "Սոնետ  128": "Սոնետ 128",
    "Սոնետ  129": "Սոնետ 129",
    "Սոնետ  130": "Սոնետ 130",
    "Սոնետ  131": "Սոնետ 131",
    "Սոնետ  132": "Սոնետ 132",
    "Սոնետ  133": "Սոնետ 133",
    "Սոնետ  134": "Սոնետ 134",
    "Սոնետ  135": "Սոնետ 135",
    "Սոնետ  136": "Սոնետ 136",
    "Սոնետ  137": "Սոնետ 137",
    "Սոնետ  138": "Սոնետ 138",
    "Սոնետ  139": "Սոնետ 139",
    "Սոնետ  140": "Սոնետ 140",
    "Սոնետ  141": "Սոնետ 141",
    "Սոնետ  142": "Սոնետ 142",
    "Սոնետ  143": "Սոնետ 143",
    "Սոնետ  144": "Սոնետ 144",
    "Սոնետ  145": "Սոնետ 145",
    "Սոնետ  146": "Սոնետ 146",
    "Սոնետ  147": "Սոնետ 147",
    "Սոնետ  148": "Սոնետ 148",
    "Սոնետ  149": "Սոնետ 149",
    "Սոնետ  150": "Սոնետ 150",
    "Սոնետ  151": "Սոնետ 151",
    "Սոնետ  152": "Սոնետ 152",
    "Սոնետ  153": "Սոնետ 153",
    "Սոնետ  154": "Սոնետ 154",
    "vahan-teryan/ananun ser": "Անանուն սեր",
    "vahan-teryan/ashnan erg": "Աշնաներգ",
    "vahan-teryan/Աշուն Է անձրև": "Աշուն է, անձրև",
    "vahan-teryan/es chgitem ur en tanum heravor": "Ես չգիտեմ ուր են տանում հեռավոր",
    "vahan-teryan/es sirum em qo meravor achqery xor": "Ես սիրում եմ քո մեղավոր աչքերը խոր",
    "vahan-teryan/elegia": "Էլեգիա",
    "vahan-teryan/estonakan": "Էստոնական",
    "vahan-teryan/im xarar erekon e hima": "Իմ խաղաղ երեկոն է հիմա",
    "vahan-teryan/iriknajam": "Իրիկնաժամ",
    "vahan-teryan/xarar gisherov du kgas inz mot": "Խաղաղ գիշերով դու կգաս ինձ մոտ",
    "vahan-teryan/xosqery vchit en u xorunk": "Խոսքերը վճիտ են ու խորունկ",
    "vahan-teryan/Կարոտ": "Կարոտ",
    "vahan-teryan/hrajeshti gazel": "Հրաժեշտի գազել",
    "vahan-teryan/hrashk argik": "Հրաշք աղջիկ",
    "vahan-teryan/mtnshar": "Մթնշաղ",
    "vahan-teryan/Մոռանալ": "Մոռանալ",
    "vahan-teryan/sentimental erg": "Սենտիմենտալ երգ",
    "vahan-teryan/sev gisher e noric u husher anhamar": "Սև գիշեր է նորից ու հուշեր անհամար",
    "vahan-teryan/qo achqeri dem im achqery kujr": "Քո աչքերի դեմ իմ աչքերը կույր",
    "vahan-teryan/Autumn and Rain  Աշուն Է անձրև": "Autumn and Rain (Աշուն է, անձրև)",
    "vahan-teryan/Golden Stars in Blue(Տխուր զրույց)": "Golden Stars in Blue (Տխուր զրույց)",
    "hamo-sahyan/axr es inchpes ver kenam gnam": "Ախր ես ինչպես վեր կենամ գնամ",
    "hamo-sahyan/amen aravot": "Ամեն առավոտ",
    "hamo-sahyan/Ամպ է Նորից": "Ամպ է Նորից",
    "hamo-sahyan/anzrev": "Անձրև",
    "hamo-sahyan/anund talis": "Անունդ տալիս",
    "hamo-sahyan/arajin ser": "Առաջին սերս",
    "hamo-sahyan/guce henc ajster": "Գուցե հենց այստեղ",
    "hamo-sahyan/du inz torel eir menak": "Դու ինձ թողել էիր մենակ",
    "hamo-sahyan/duq lavn eq mardiq": "Դուք լավն եք, մարդիկ",
    "hamo-sahyan/es kuzei ": "Ես կուզեի",
    "hamo-sahyan/es chem karogh chnershnchvel": "Ես չեմ կարող չներշնչվել",
    "hamo-sahyan/es chem karogh chnershnchvel roc": "Ես չեմ կարող չներշնչվել (ռոք)",
    "hamo-sahyan/es u du": "Ես և դու",
    "hamo-sahyan/ev chimacanq te inchu": "Եվ չիմացանք թե ինչու",
    "hamo-sahyan/torvochvoqi chkanchen": "Թող ոչ ոքի չկանչեն",
    "hamo-sahyan/tor vochvoqi chkanchen02roc": "Թող ոչ ոքի չկանչեն (02 ռոք)",
    "hamo-sahyan/torvochvoqi chkanchen roc": "Թող ոչ ոքի չկանչեն (ռոք)",
    "hamo-sahyan/inch anem mairik": "Ի՞նչ անեմ, մայրիկ",
    "hamo-sahyan/inch taqcnem": "Ի՞նչ թաքցնեմ",
    "hamo-sahyan/inch arac mard em": "Ինչ արած, մարդ եմ",
    "hamo-sahyan/inchu hishecri": "Ինչու հիշեցրի",
    "hamo-sahyan/covn er gisher er es ei u du": "Ծովն էր, գիշերն էր, ես էի և դու",
    "hamo-sahyan/ka mi tulutun": "Կա մի թուլություն",
    "hamo-sahyan/kanch": "Կանչ",
    "hamo-sahyan/kgam": "Կգամ",
    "hamo-sahyan/hajastan aselis": "Հայաստան ասելիս",
    "hamo-sahyan/hajastan aselis roc": "Հայաստան ասելիս (ռոք)",
    "hamo-sahyan/hognel em": "Հոգնել եմ",
    "hamo-sahyan/horovely": "Հորովելը",
    "hamo-sahyan/mer lezun": "Մեր լեզուն",
    "hamo-sahyan/mitegh ishxan u ter": "Մի տեղ իշխան ու տեր",
    "hamo-sahyan/mijocners": "Միջոցներս",
    "hamo-sahyan/vochinch chi poxvi": "Ոչինչ չի փոխվի",
    "hamo-sahyan/um hamar im ushqy gnac": "Ում համար իմ ուշքը գնաց",
    "hamo-sahyan/ches asi voch mi barov": "Չես ասի ոչ մի բարով",
    "hamo-sahyan/papy": "Պապը",
    "hamo-sahyan/vshtacel em amen inchic": "Վշտացել եմ ամեն ինչ",
    "hamo-sahyan/tar inz jamanak": "Տար ինձ ժամանակ",
    "hamo-sahyan/tar inz jamanak roc": "Տար ինձ ժամանակ (ռոք)",
    "hamo-sahyan/Փնտրում ես դու": "Փնտրում ես դու",
    "hamo-sahyan/qamu hamburic": "Քամու համբյուրից",
    "hamo-sahyan/How Can I Just Leave": "How Can I Just Leave",
    "hamo-sahyan/I Will Come Anyway": "I Will Come Anyway",
    "hamo-sahyan/My First Love": "My First Love",
    "hamo-sahyan/Our Language": "Our Language",
    "hamo-sahyan/The Forest's Whisper": "The Forest's Whisper",
    "hamo-sahyan/The One in Vain": "The One in Vain",
    "hamo-sahyan/The Thunderstorm": "The Thunderstorm",
    "hamo-sahyan/vsio ravno pridu": "Всё равно я приду",
    "hamo-sahyan/vsem kem ya bil": "Всё, кем я был",
    "hamo-sahyan/dojd": "Дождь",
    "hamo-sahyan/dojd roc": "Дождь (рок)",
    "hamo-sahyan/kak je mne uyti": "Как же мне уйти",
    "hamo-sahyan/mama": "Мама",
    "hamo-sahyan/moi sredstva moi zaboti": "Мои средства... Мои заботы...",
    "hamo-sahyan/moya neprojitaya jizn": "Моя непрожитая жизнь",
    "hamo-sahyan/nash yazik": "Наш язык",
    "hamo-sahyan/pervaya lubov": "Первая любовь моя",
    "hamo-sahyan/paceluy vetra": "Поцелуй ветра",
    "hamo-sahyan/proshay": "Прощай",
    "hamo-sahyan/uznat menya ne tak prosto": "Узнать меня совсем непросто",
    "hamo-sahyan/chto bilo to bilo": "Что было, то было",
    "hamo-sahyan/ya xotel razdeliat": "Я хотел бы разделять с тобой",
    "hamo-sahyan/Հայոց փշատենին": "Հայոց փշատենին",
    "hamo-sahyan/Հայոց փշատենին ջազ": "Հայոց փշատենին (ջազ)",
    "parujr-sevak/erku siro aranqum": "Երկու սիրո արանքում",
    "parujr-sevak/erku siro aranqum roc": "Երկու սիրո արանքում (ռոք)",
    "parujr-sevak/menq qich enq sakajn mez haj en asum": "Մենք քիչ ենք, սակայն մեզ հայ են ասում",
    "parujr-sevak/miangamic roc": "Միանգամից (ռոք)",
    "parujr-sevak/miangamic tango": "Միանգամից (տանգո)",
    "parujr-sevak/Նախանձում եմ": "Նախանձում եմ",
    "parujr-sevak/ՍԵՐՆ ԻՆՉ ԳՈՒՅՆ ՈՒՆԻ": "Սերն ինչ գույն ունի",
    "parujr-sevak/What Color Is Love": "What Color Is Love",
    "parujr-sevak/Какого цвета любовь": "Какого цвета любовь",
    "avetik-isahakyan/Ախ կուզես լինիմ": "Ախ կուզես լինիմ",
    "aramayis-sahakyan/Ես կուզեի քո ճանապարհին": "Ես կուզեի քո ճանապարհին",
    "shiraz/Իմ պատանի սիրտս": "Իմ պատանի սիրտս",
    "silva-kaputikyan/Լուսինն ու Արևը": "Լուսինն ու Արևը",
    "silva-kaputikyan/Ծուխը չերևա": "Ծուխը չերևա",
    "silva-kaputikyan/Ոչ մեր սիրելն էր նման սիրելու": "Ոչ մեր սիրելն էր նման սիրելու",
    "silva-kaputikyan/Սեր": "Սեր",
    "silva-kaputikyan/Քեզ փնտրում եմ": "Քեզ փնտրում եմ",
    "silva-kaputikyan/The Moons Jealousy": "The Moon's Jealousy",
    "silva-kaputikyan/Белая Луна": "Белая Луна",
    "vahagn-davtyan/Սեր": "Սեր",
    "hovhannes-tumanyan/Սիրում էի երբեմն քեզ": "Սիրում էի երբեմն քեզ",
    "shiraz/Սիրո համար մահ չկա": "Սիրո համար մահ չկա",
    "shiraz/Հայոց լեզուն": "Հայոց լեզուն",
    "shiraz/Սիրո հիասթափություն": "Սիրո հիասթափություն",
    "shiraz/Իմ Սուրբ Հայրենիք": "Իմ Սուրբ Հայրենիք",
    "shiraz/Դու իմ միակ աստվածուհի": "Դու իմ միակ աստվածուհի",
    "shiraz/Դու էլ ի՛մն ես": "Դու էլ ի՛մն ես"
  },
  byLang: {
    "andadar carav": {"en":"Endless Thirst","ru":"Неустанная жажда"},
    "Astghayin_Shghta_A": {"en":"Starry Chain","ru":"Звёздная цепь"},
    "The Sun Cries Too(Արևն էլ է լաց լինում)": {"en":"The Sun Cries Too","ru":"Солнце тоже плачет"},
    "Vahan_Teryan_Gisher": {"en":"Night (V. Teryan)","ru":"Ночь (В. Терян)"},
    "B_Es_im_anush_Hayastani": {"en":"My Sweet Armenia","ru":"Моя милая Армения"},
    "ergi chapov": {"en":"By a Song's Measure","ru":"Мерой песни"},
    "El_ban_chunem_Remix": {"en":"I Have Nothing Else","ru":"У меня больше ничего нет"},
    "taxicy vat margare e": {"en":"Sadness Is a Bad Prophet","ru":"Печаль — плохой пророк"},
    "Իմ Գեղեցկուհի ընկերուհիները": {"en":"My Beautiful Girlfriends","ru":"Мои красивые подруги"},
    "Իմ Գեղեցկուհի ընկերուհիները twist rock & roil": {"en":"My Beautiful Girlfriends (Twist Rock & Roll)","ru":"Мои красивые подруги (Твист Рок-н-ролл)"},
    "Իմ Գեղեցկուհի ընկերուհիներըroc&roil": {"en":"My Beautiful Girlfriends (Rock & Roll)","ru":"Мои красивые подруги (Рок-н-ролл)"},
    "im ser": {"en":"My Love","ru":"Моя любовь"},
    "inchi-hamar": {"en":"What For","ru":"Для чего"},
    "inch_e_koracy_qarcr": {"en":"Why Does What's Lost Grow So Sweet","ru":"Почему потерянное становится таким сладким"},
    "lur-heraxos": {"en":"Silent Phone","ru":"Молчаливый телефон"},
    "lur uji simfonia": {"en":"Symphony of Silent Strength","ru":"Симфония тихой силы"},
    "luse arzaganq": {"en":"Luminous Echo","ru":"Светлое эхо"},
    "Luse_Hekiat_A": {"en":"Luminous Tale","ru":"Светлая сказка"},
    "Lrutyan_unker": {"en":"Friend of Silence","ru":"Друг тишины"},
    "Lsir_vordis": {"en":"Listen, My Son","ru":"Слушай, сын мой"},
    "Կատակ յարի երգ պար 4 լեզվով": {"en":"Playful Sweetheart's Song-Dance in 4 Languages","ru":"Шуточный танец-песня о возлюбленной на 4 языках"},
    "Katak_Yari_Ergu": {"en":"The Playful Sweetheart's Song","ru":"Песня шутливой любимой"},
    "Կատակ Յարի Երգը": {"en":"Roses in a Sieve","ru":"Песня-шутка"},
    "Katak_Yari_Ergu rem": {"en":"The Playful Sweetheart's Song (Remix)","ru":"Песня шутливой любимой (Ремикс)"},
    "haverji-erty": {"en":"Song of Eternity","ru":"Песня вечности"},
    "hogu-arzaganq": {"en":"Echo of the Soul","ru":"Эхо души"},
    "Մեղքի եզրին": {"en":"On the Edge of Sin","ru":"Между страстью и грехом"},
    "On the Edge of Sin": {"hy":"Մեղքի եզրին","ru":"Между страстью и грехом"},
    "Meghki_ezrin_Remix": {"en":"On the Edge of Sin","hy":"Մեղքի եզրին"},
    "Նախանձում եմ": {"en":"I Envy","ru":"Я завидую"},
    "shshnjatc": {"en":"Whispered","ru":"Прошептала"},
    "shshnjatc-noric": {"en":"Whispered Again","ru":"Прошептала снова"},
    "shepot": {"hy":"Շշունջ","en":"Whisper"},
    "Ջրահարսեր Ремикс Ремикс_2": {"en":"Mermaids Remix 2","ru":"Русалки Ремикс 2"},
    "Ջրահարսեր Ремикс Ремикс_3": {"en":"Mermaids Remix 3","ru":"Русалки Ремикс 3"},
    "ser-anurji": {"en":"Love of a Dream","ru":"Любовь мечты"},
    "sirelis": {"en":"My Dear","ru":"Любимая"},
    "siro-kenacy": {"en":"Toast to Love","ru":"Тост за любовь"},
    "Поцелуй_ветра": {"en":"The Wind's Kiss (H. Sahyan)","ru":"Поцелуй ветра (О. Саакян)"},
    "Vahan_Teryan_MEGhAVOR_AChKERU": {"en":"Your Guilty Eyes (V. Teryan)","ru":"Твои виноватые глаза (В. Терян)"},
    "qo-jinj-hogin": {"en":"Your Pure Soul","ru":"Твоя чистая душа"},
    "A Song Away": {"hy":"Երգի Չափով","ru":"На расстоянии песни"},
    "IM JEALOUS OF THE MOSQUITO": {"hy":"Նախանձում եմ մոծակին","ru":"Ревную к комару"},
    "Our Lovely Mermaids": {"hy":"Մեր հրաշալի ջրահարսերը","ru":"Эй наши русалки"},
    "Roses in a Sieve": {"hy":"Կատակ Յարի Երգը","ru":"Песня шутка"},
    "The Eternal Thirst": {"hy":"Անդադար ծարավ","ru":"Постоянная жажда"},
    "На расстоянии песни": {"hy":"Երգի Չափով","en":"A Song Away"},
    "Песня шутка": {"hy":"Կատակ Յարի Երգը","en":"Roses In A Sieve"},
    "pastayannaya jajda": {"hy":"Անդադար ծարավ","en":"The Eternal Thirst"},
    "Ревую к комару": {"hy":"Նախանձում եմ մոծակին","en":"I'm Jealous of the Mosquito"},
    "Эй наши русалки": {"hy":"Մեր հրաշալի ջրահարսերը","en":"Our Lovely Mermaids"},
    "Ρόδα στο Κόσκινο": {"hy":"Կատակ Յարի Երգը","en":"Roses In A Sieve","ru":"Песня шутка"},
    "ვარდები საცერში": {"hy":"Կատակ Յարի Երգը","en":"Roses In A Sieve","ru":"Песня шутка"},
    "ჩვენი ქალთევზებო": {"hy":"Մեր ջրահարսերը","en":"Our Mermaids","ru":"Наши русалки"},
    "Akh_inch_anem_sirud_het": {"en":"Oh, What Should I Do With Your Love","ru":"Ах, что мне делать с твоей любовью"},
    "agh & dagy": {"en":"Salt and the Wound","ru":"Соль и рана"},
    "Andzrevum_e": {"en":"It's Raining","ru":"Идёт дождь"},
    "Mtnets_arants_kez_Duet": {"en":"It Grew Dark Without You","ru":"Стемнело без тебя"},
    "ari-khmenq": {"en":"Come, Let's Drink","ru":"Давай выпьем"},
    "Ari_klini": {"en":"Come, It Will Be Fine","ru":"Приходи, всё будет хорошо"},
    "Aryev_darnam": {"en":"Let Me Become the Sun","ru":"Пусть я стану солнцем"},
    "byur harvacneric": {"en":"From a Thousand Blows","ru":"От тысячи ударов"},
    "bjur u bjur angam": {"en":"A Thousand Times Over","ru":"Тысячу и тысячу раз"},
    "Galis_e_mi_pah_003": {"en":"A Moment Comes","ru":"Наступает миг"},
    "Garun_er_003": {"en":"It's Spring","ru":"Весна"},
    "Garun e bajc zun e arel": {"en":"It's Spring but It Snowed","ru":"Весна, но выпал снег"},
    "gereckuhi": {"en":"Beautiful Woman","ru":"Красавица"},
    "gjuk lusiny": {"en":"Crazy Little Moon","ru":"Сумасшедшая луна"},
    "gij": {"en":"Crazy","ru":"Безумная"},
    "gij-qamin": {"en":"Crazy Wind","ru":"Безумный ветер"},
    "Gisher_e_004": {"en":"It's Night","ru":"Ночь"},
    "Gisherits_depi_luys_Silva_Gulanyan_005": {"en":"From Night to Light","ru":"От ночи к свету"},
    "gitem el inz ches spasum": {"en":"I Know You're No Longer Waiting for Me","ru":"Знаю, ты меня больше не ждёшь"},
    "Gitem_hogis_A": {"en":"I Know, My Soul","ru":"Знаю, душа моя"},
    "Gitem_ches_galu_B": {"en":"I Know You Won't Come","ru":"Знаю, ты не придёшь"},
    "gortrik-ankun": {"en":"Secret Corner","ru":"Тайный уголок"},
    "Դավաճան հայ": {"en":"Traitor Armenian","ru":"Армянин-предатель"},
    "der-inz-voch-mek-chi-sirel-qo-pes": {"en":"No One Has Loved Me Like You","ru":"Никто ещё не любил меня так, как ты"},
    "Դու իմ աշխարհն ես": {"en":"You Are My World","ru":"Ты мой мир"},
    "Dran_Takotsu_003": {"en":"A Knock at the Door","ru":"Стук в дверь"},
    "ete asem": {"en":"If I Should Say","ru":"Если я скажу"},
    "Եղբայր իմ անգին": {"en":"My Precious Brother","ru":"Мой бесценный брат"},
    "Es_irakan_em_004": {"en":"I Am Real","ru":"Я настоящая"},
    "Es_sirum_em_ko_zhpitu_B": {"en":"I Love Your Smile","ru":"Я люблю твою улыбку"},
    "Es_kez_sirum_em": {"en":"I Love You","ru":"Я люблю тебя"},
    "Erazankneri_aytsu_Part_Gisherva_002": {"en":"A Night Visit of Dreams","ru":"Ночной визит грёз"},
    "erazi kyanq": {"en":"Station of Dreams","ru":"Станция мечты"},
    "erazi kyamq roc": {"en":"Station of Dreams (Rock)","ru":"Станция мечты (рок)"},
    "Երանի գայիր(Just Like Before)": {"en":"I Wish You'd Come, Just Like Before","ru":"Если бы ты пришла, как прежде"},
    "Erb_verkers_hanger_dardzri_Lyrics_by_Silva_Gulanyan_003": {"en":"When My Songs Turned to Embers","ru":"Когда мои песни стали углями"},
    "ergichy-dari": {"en":"The Singer's Era","ru":"Эпоха певца"},
    "Erku_khent_hogi_Duet_Silva_Gulanyan_004": {"en":"Two Crazy Souls","ru":"Две безумные души"},
    "Թախծիս անունը": {"en":"The Name of My Sorrow","ru":"Имя моей печали"},
    "Թախծիս անունը_1": {"en":"The Name of My Sorrow (Tango)","ru":"Имя моей печали (Танго)"},
    "Թանկ հուշը": {"en":"The Precious Memory","ru":"Дорогое воспоминание"},
    "te karotum es": {"en":"If You Miss Me","ru":"Если ты скучаешь"},
    "jpta hogis": {"en":"Smile, My Soul","ru":"Улыбнись, душа моя"},
    "Im_erazats_ashkharu_003": {"en":"In the World I Dreamed Of","ru":"В мире, о котором я мечтала"},
    "im-tsovagur": {"en":"My Seaside Village","ru":"Моя приморская деревня"},
    "Իմ Քնքուշ Սևան": {"en":"My Tender Sara","ru":"Моя нежная Сара"},
    "inch-em-anelu": {"en":"What Am I Going to Do","ru":"Что мне делать"},
    "inchu_es_ayskan_indz_otar_dardzel_004": {"en":"Why Have You Become So Distant to Me","ru":"Почему ты стал мне таким чужим"},
    "lok cav u dard": {"en":"Just Pain and Sorrow","ru":"Лишь боль и печаль"},
    "luse hrashq": {"en":"Miracle of Light","ru":"Чудо света"},
    "lrutian tchich": {"en":"A Cry of Silence","ru":"Крик тишины"},
    "xararutun ber": {"en":"Bring Peace","ru":"Принеси мир"},
    "xerdvac karot": {"en":"Suffocated Longing","ru":"Задушенная тоска"},
    "xerdvac karot patasxan": {"en":"Suffocated Longing (Reply)","ru":"Задушенная тоска (ответ)"},
    "խենթ խաղեր": {"en":"Crazy Games","ru":"Безумные игры"},
    "xent siro qamin": {"en":"The Wind of Crazy Love","ru":"Ветер безумной любви"},
    "xentern u lusiny": {"en":"The Madmen and the Moon","ru":"Безумцы и луна"},
    "խենթի նման սիրահարվեցի": {"en":"I Fell in Love Like a Madwoman","ru":"Влюбилась, как безумная"},
    "xind manuk": {"en":"Joyful Child","ru":"Радостное дитя"},
    "xortakvor nav": {"en":"Sinking Ship","ru":"Тонущий корабль"},
    "tsov-arev-achqer": {"en":"Sea, Sun, Eyes","ru":"Море, солнце, глаза"},
    "Ծովի մեջ աչքերդ": {"en":"Your Eyes in the Sea","ru":"Твои глаза в море"},
    "Mer_Srterum_kanchu_004": {"en":"A Call in Our Hearts","ru":"Зов в наших сердцах"},
    "Կարոտի խենթի": {"en":"The Madness of Longing","ru":"Безумие тоски"},
    "karotiali shurterin": {"en":"On the Lips of Longing","ru":"На губах тоски"},
    "kgam_sirelis": {"en":"I Will Come, My Love","ru":"Я приду, любимый"},
    "Kenatsd_khmem_B_Brinderò_per_Te": {"en":"Let Me Drink to You","ru":"Выпью за тебя"},
    "Kuratsats_achkin_luysu_003": {"en":"Light of a Blinded Eye","ru":"Свет ослеплённого глаза"},
    "Hay_aragil": {"en":"Armenian Stork","ru":"Армянский аист"},
    "Hayots_ashkarh_A": {"en":"Armenian World","ru":"Мир армян"},
    "Havat_em_vozum_003": {"en":"I Want Faith","ru":"Я хочу веры"},
    "HERO_MOTIK_UNKERNERIS_003": {"en":"To My Friends, Near and Far","ru":"Моим друзьям, близким и далёким"},
    "Hetd_inch_e_katarvum": {"en":"What's Happening to You","ru":"Что с тобой происходит"},
    "RokHetd_Inch_E_Katarvum_003": {"en":"What's Happening to You (Rock)","ru":"Что с тобой происходит (рок)"},
    "hiastapvac": {"en":"Disappointed","ru":"Разочарованная"},
    "hima": {"en":"Now","ru":"Сейчас"},
    "hogu giny": {"en":"The Price of the Land","ru":"Цена земли"},
    "Kyanku_Hrashk_e_005": {"en":"Miracle Life","ru":"Чудо-жизнь"},
    "Dzig_tarineri_luys_003": {"en":"Light Through the Long Years","ru":"Свет долгих лет"},
    "Tchaxr e pargevum ": {"en":"It Grants Flight","ru":"Дарит полёт"},
    "Chisht_zhamanakin_At_The_Right_Time": {"en":"At the Right Time","ru":"В нужное время"},
    "mek tari el ancav": {"en":"Another Year Has Passed","ru":"Прошёл ещё один год"},
    "mern zepur": {"en":"The Gentle Breeze","ru":"Нежный ветерок"},
    "Title_Mi_tanjir_hogis_Multilingual_Emotional_Duet_Lyrics_by_Silva_Gulanyan_002": {"en":"Don't Torment My Soul","ru":"Не мучай мою душу"},
    "Resta_nei_nostri_cuori": {"en":"Stay in Our Hearts","ru":"Останься в наших сердцах"},
    "Nerir sirelis": {"en":"Forgive Me, My Love","ru":"Прости, любимый"},
    "nerqnapanak": {"en":"The Underlay","ru":"Подстилка"},
    "Nrboren_Garnunk_003": {"en":"Gently, Spring","ru":"Нежно, весна"},
    "ov em qez hamar": {"en":"Who Am I to You","ru":"Кто я для тебя"},
    "ughernery-lac-chen-linum": {"en":"Even the Strong Cry","ru":"Даже сильные плачут"},
    "Che_chem_toghni_B": {"en":"No, I Won't Let Go","ru":"Нет, я не отпущу"},
    "chem moracel": {"en":"I Haven't Forgotten","ru":"Я не забыла"},
    "Ches_moranalu_003": {"en":"You Won't Forget","ru":"Ты не забудешь"},
    "Jaheli_nman_003": {"en":"Like Someone Young","ru":"Как молодая"},
    "Tiezerk_Jinj_Lazur": {"en":"Clear Universe","ru":"Ясная вселенная"},
    "ser da ardioq": {"en":"Is This Really Love","ru":"Неужели это любовь"},
    "ser eir xarum": {"en":"You Were Playing at Love","ru":"Ты играл в любовь"},
    "Սիրել հենց հոգուն": {"en":"To Love the Soul Itself","ru":"Любить именно душу"},
    "Սիրել հենց հոգուն (1)": {"en":"To Love the Soul Itself (1)","ru":"Любить именно душу (1)"},
    "Sirir_indz_hogis_FRAM_Duet": {"en":"Love Me, My Soul","ru":"Люби меня, душа моя"},
    "melodia lubvi": {"en":"Music of Love","ru":"Музыка любви"},
    "siro cnundy": {"en":"Birth of Love","ru":"Рождение любви"},
    "S_irum_em_kez_I_love_you": {"en":"I Love You","ru":"Я люблю тебя"},
    "sirty xentacav": {"en":"My Heart Went Mad","ru":"Моё сердце обезумело"},
    "Srteri_kanchu_003": {"en":"Call of the Hearts","ru":"Зов сердец"},
    "Ka_mi_ashkharh_vor_srtov_e_karutsvats": {"en":"A World Built With Heart","ru":"Мир, построенный сердцем"},
    "Tesilk_Silva_Gulanyan_Remix_Remix": {"en":"Vision","ru":"Видение"},
    "Տիեզերական կինը": {"en":"The Cosmic Woman","ru":"Космическая женщина"},
    "Տիեզերական կինը (Remastered)": {"en":"The Cosmic Woman (Remastered)","ru":"Космическая женщина (Ремастер)"},
    "Տիեզերական կինը roc": {"en":"The Cosmic Woman (Rock)","ru":"Космическая женщина (рок)"},
    "cav anbujeli": {"en":"Incurable Pain","ru":"Неизлечимая боль"},
    "AKhor_vo_tsavits_tsnvats": {"en":"Born From Pain","ru":"Рождённая из боли"},
    "Curt xavaric": {"en":"From the Cold Darkness","ru":"Из холодной тьмы"},
    "Քեզ դուրս եմ արել": {"en":"I've Shut You Out","ru":"Я тебя выгнала"},
    "Kez_khenti_nman_siraharvetsi_Duet_Tango": {"en":"I Fell for You Like a Madwoman (Duet Tango)","ru":"Влюбилась в тебя как безумная (Дуэт Танго)"},
    "qez karotelis": {"en":"While Missing You","ru":"Скучая по тебе"},
    "Քեզ կարոտելիս": {"en":"While Missing You","ru":"Скучая по тебе"},
    "qo cov achqeri kajcern em sirum": {"en":"I Love the Spark in Your Eyes","ru":"Люблю искру в твоих глазах"},
    "qo_drakhtum_002": {"en":"In Your Paradise","ru":"В твоём раю"},
    "Քո ժպիտները հավաքեմ": {"en":"Let Me Gather Your Smiles","ru":"Дай мне собрать твои улыбки"},
    "Ko_koghkin_vorish_em_003": {"en":"Beside You, I'm Someone Else","ru":"Рядом с тобой я другая"},
    "Ko_hmayki_gerin": {"en":"Captive of Your Charm","ru":"Пленница твоего очарования"},
    "Kuyr_eghbayr_003": {"en":"Sister and Brother","ru":"Сестра и брат"},
    "ov e kimy": {"en":"Who Is the Woman","ru":"Кто эта женщина"},
    "frants_Harbel_em_vozum": {"en":"I Want to Get Drunk in French","ru":"Хочу напиться по-французски"},
    "Crazy Breeze of Love": {"hy":"Խենթ սիրո քամին","ru":"Безумный Ветер Любви"},
    "I Gave My Sorrow The Name": {"hy":"Թախծիս անունը դրեցի","ru":"Я назвал свою печаль тоской"},
    "Longing for You": {"hy":"Քեզ կարոտելիս","ru":"Тоскуя по тебе"},
    "Love Unseen": {"hy":"Սիրել հենց հոգուն","ru":"Любить лишь душу"},
    "Love Unseen (1)": {"hy":"Սիրել հենց հոգուն (1)","ru":"Любить лишь душу (1)"},
    "My Bright Dream": {"hy":"Իմ պայծառ երազանքը","ru":"Моя светлая мечта"},
    "My Bright Dream (1)": {"hy":"Իմ պայծառ երազանքը (1)","ru":"Моя светлая мечта (1)"},
    "My Endless Dream": {"hy":"Իմ անվերջ երազանքը","ru":"Моя бесконечная мечта"},
    "My Only Light": {"hy":"Իմ միակ լույսը","ru":"Мой светлый луч"},
    "My Precious Love": {"hy":"Իմ թանկագին սերը","ru":"Моя драгоценная любовь"},
    "My Precious Love драгоценная любовь": {"hy":"Իմ թանկագին սերը","en":"My Precious Love"},
    "Never a Stranger": {"hy":"Երբեք անծանոթ","ru":"Никогда не чужой"},
    "Powerless Against Memories": {"hy":"Անզոր հիշողությունների առաջ","ru":"Перед памятью злой"},
    "The Illusion of Longing": {"hy":"Կարոտի պատրանքը","ru":"Образы тоски"},
    "The Night's Embrace": {"hy":"Գիշերվա գիրկը","ru":"Объятия ночи"},
    "The Song of the Spring Breeze": {"hy":"Կարոտի խենթի","ru":"Тоска по мне"},
    "The Sun Cries Too": {"hy":"Արևն էլ է լաց լինում","ru":"Солнце тоже плачет"},
    "The Woman as the Universe": {"hy":"Տիեզերական կինը","ru":"Женщина-вселенная"},
    "You Are My World": {"hy":"Դու իմ աշխարհն ես","ru":"Ты мой мир"},
    "Безумный Ветер Любви": {"hy":"Խենթ սիրո քամին","en":"Crazy Breeze of Love"},
    "Любить лишь душу": {"hy":"Սիրել հենց հոգուն","en":"Love Unseen"},
    "Любить лишь душу (1)": {"hy":"Սիրել հենց հոգուն (1)","en":"Love Unseen (1)"},
    "Мой светлый луч": {"hy":"Իմ միակ լույսը","en":"My Only Light"},
    "Образы тоски": {"hy":"Կարոտի պատրանքը","en":"The Illusion of Longing"},
    "Перед памятью злой": {"hy":"Անզոր հիշողությունների առաջ","en":"Powerless Against Memories"},
    "Светлый полёт": {"hy":"Պայծառ թռիչք","en":"Bright Flight"},
    "Сокровенный причал": {"hy":"Գաղտնի նավահանգիստը","en":"The Secret Harbor"},
    "Тоска по мне": {"hy":"Կարոտի խենթի","en":"The Song of the Spring Breeze"},
    "Тоскуя по тебе": {"hy":"Քեզ կարոտելիս","en":"Longing for You"},
    "ti moy kislarod": {"hy":"Դու իմ թթվածինն ես","en":"You Are My Oxygen"},
    "Ты мой мир": {"hy":"Դու իմ աշխարհն ես","en":"You Are My World"},
    "ti pridyosh komne": {"hy":"Դու կգաս ինձ մոտ","en":"You Will Come to Me"},
    "Я назвал свою печаль тоской": {"hy":"Թախծիս անունը դրեցի","en":"I Gave My Sorrow The Name"},
    "Խղճում եմ նրանց": {"en":"I Pity Them","ru":"Мне жаль их"},
    "Ուզում եմ նորից մանկանալ": {"en":"I Want to Be a Child Again","ru":"Хочу снова стать ребёнком"},
    "Ոսկե աշուն": {"en":"Golden Autumn","ru":"Золотая осень"},
    "Աշնան Վալսը Պուրակում": {"en":"Autumn Waltz in the Park","ru":"Осенний вальс в парке"},
    "Ես չգիտեմ քե՞զ եմ սիրում": {"en":"I Don't Know, Is It You I Love?","ru":"Не знаю, тебя ли я люблю?"},
    "ajs xarum mian ujern e haxtum": {"en":"In This Game the Strong Wins","ru":"В этой игре побеждает сильный"},
    "Anund_Kin_e_004": {"en":"Your Name Is Woman","ru":"Твоё имя — женщина"},
    "Անունդ կին է ֆրի տանգո": {"en":"Your Name Is Woman (Tango)","ru":"Твоё имя — женщина (танго)"},
    "Arajin_hambuyru": {"en":"First Kiss","ru":"Первый поцелуй"},
    "Arevamutits_araj": {"en":"Before Sunset","ru":"Перед закатом"},
    "Bari_gisher": {"en":"Good Night","ru":"Спокойной ночи"},
    "duet_Спокойной_ночи_Remix_Remix": {"en":"Good Night (Duet)","ru":"Спокойной ночи (дуэт)"},
    "spakojnoj nochi (kin)": {"en":"Good Night (Russian)","ru":"Спокойной ночи"},
    "Ginin_prprel_e": {"en":"The Wine Has Foamed","ru":"Вино вспенилось"},
    "gisherajin": {"en":"Nocturnal","ru":"Ночной"},
    "darnaham-ginin": {"en":"Bitter Wine","ru":"Горькое вино"},
    "daravor karnin": {"en":"Ancient Oak","ru":"Вековой дуб"},
    "Դու եկար": {"en":"You Came","ru":"Ты пришёл"},
    "Title_Es_arajva_pes_kez_karotum_em_Swiss_Pop_Ballad_Lyrics_by_Go_Hara_Remix_008": {"en":"I Miss You Like Before","ru":"Я скучаю по тебе, как прежде"},
    "Եվ ինչ է սերը": {"en":"And What Is Love","ru":"И что такое любовь"},
    "Իմ հայելի": {"en":"My Mirror","ru":"Моё зеркало"},
    "Im_poezian": {"en":"My Poetry","ru":"Моя поэзия"},
    "la-fracise": {"en":"La France","ru":"Ля Франс"},
    "pered rasvetom": {"en":"Before Dawn","ru":"Перед рассветом"},
    "kanchir-kgam": {"en":"Call and I'll Come","ru":"Позови, я приду"},
    "Հայաստան, մեր սուրբ տուն": {"en":"Armenia, Our Sacred Home","ru":"Армения, наш святой дом"},
    "HANDIPOMNERI_AYS_KhAChMEROKOM": {"en":"At This Crossroads of Meetings","ru":"На этом перекрёстке встреч"},
    "Hervits_Grkum em": {"en":"I Embrace You From Afar (Remix)","ru":"Обнимаю издалека (Ремикс)"},
    "hognel em ujer kin lineluc": {"en":"I'm Tired of Being a Strong Woman","ru":"Устала быть сильной женщиной"},
    "Hravirir_indz_parelu_tangon": {"en":"Invite Me to Dance the Tango","ru":"Пригласи меня танцевать танго"},
    "menq linelu enq": {"en":"We Are Meant to Be","ru":"Мы будем вместе"},
    "MI_TOGh_INDz_MENAK": {"en":"Don't Leave Me Alone","ru":"Не оставляй меня одну"},
    "Mi_siro_patmutyun": {"en":"A Love Story","ru":"История одной любви"},
    "urenineri lacor purakum": {"en":"In the Weeping Willow Grove","ru":"В плачущей роще ив"},
    "Չնոտագրված լռություն": {"en":"Unwritten Silence","ru":"Ненотированное молчание"},
    "POETIS": {"en":"My Poet","ru":"Мой поэт"},
    "Սիրելով գնամ": {"en":"I'll Leave Still Loving You","ru":"Я уйду любя"},
    "Sirogisher_Go_Hara": {"en":"Night of Love","ru":"Ночь любви"},
    "cncir-users": {"en":"Shake My Shoulders","ru":"Встряхни мои плечи"},
    "Փխրուն Լաց": {"en":"Fragile Cry Has Risen Like","ru":"Во мне поднялся хрупкий плач"},
    "fracuzhenka": {"en":"The French Woman","ru":"Француженка"},
    "Armenia, Our Sacred Home": {"hy":"Հայաստան, մեր սուրբ տուն","ru":"Армения, наш святой дом"},
    "Fragile Cry Has Risen Like": {"hy":"Փխրուն Լաց","ru":"Во мне поднялся хрупкий плач"},
    "Ill Leave Still Loving You": {"hy":"Սիրելով գնամ","ru":"Я уйду любя"},
    "I'm tired of being strong": {"hy":"Հոգնել եմ ուժեղ կին լինելուց","ru":"Устала быть сильной"},
    "My Mirror True": {"hy":"Իմ հայելի","ru":"Зеркало моё"},
    "You Came": {"hy":"Դու եկար","ru":"Ты пришёл"},
    "Армения, наш святой дом": {"hy":"Հայաստան, մեր սուրբ տուն","en":"Armenia, Our Sacred Home"},
    "Во мне поднялся хрупкий плач": {"hy":"Փխրուն Լաց","en":"Fragile Cry Has Risen Like"},
    "Зеркало моё": {"hy":"Իմ հայելի","en":"My Mirror True"},
    "Ты пришёл": {"hy":"Դու եկար","en":"You Came"},
    "устала быть сильной": {"hy":"Հոգնել եմ ուժեղ կին լինելուց","en":"I'm Tired of Being Strong"},
    "Я уйду любя": {"hy":"Սիրելով գնամ","en":"I'll Leave Still Loving You"},
    "Սոնետ 1": {"hy":"Գեղեցկությունը պետք է վերարտադրվի","en":"Sonnet 1","ru":"Сонет 1"},
    "Սոնետ 2": {"hy":"Երիտասարդության անցողիկությունը և ժառանգի կարևորությունը","en":"Sonnet 2","ru":"Сонет 2"},
    "Սոնետ 3": {"hy":"Հայելու մեջ մոր դեմքը՝ կոչ ունենալու զավակ","en":"Sonnet 3","ru":"Сонет 3"},
    "Սոնետ 4": {"hy":"Անշահախնդիր վատնված գեղեցկություն","en":"Sonnet 4","ru":"Сонет 4"},
    "Սոնետ 5": {"hy":"Ժամանակը կավերի գեղեցկությունը","en":"Sonnet 5","ru":"Сонет 5"},
    "Սոնետ 6": {"hy":"Ձմռան գալուստից առաջ պահպանել գեղեցկությունը","en":"Sonnet 6","ru":"Сонет 6"},
    "Սոնետ 7": {"hy":"Արևի ուղին՝ կյանքի փուլերի այլաբանություն","en":"Sonnet 7","ru":"Сонет 7"},
    "Սոնետ 8": {"hy":"Երաժշտության ներդաշնակությունը՝ ընտանիքի խորհրդանիշ","en":"Sonnet 8","ru":"Сонет 8"},
    "Սոնետ 9": {"hy":"Այրու արցունքի վախը՝ մենակության դեմ","en":"Sonnet 9","ru":"Сонет 9"},
    "Սոնետ 10": {"hy":"Ուրիշներին չսիրելու ամոթը","en":"Sonnet 10","ru":"Сонет 10"},
    "Սոնետ 11": {"hy":"Քո զավակի մեջ կշարունակվես","en":"Sonnet 11","ru":"Сонет 11"},
    "Սոնետ 12": {"hy":"Ժամացույցի հաշվարկը՝ միայն զավակը հաղթում է ժամանակին","en":"Sonnet 12","ru":"Сонет 12"},
    "Սոնետ  13": {"hy":"Գեղեցկությունը վարձակալված է, ոչ սեփականություն","en":"Sonnet 13","ru":"Сонет 13"},
    "Սոնետ  14": {"hy":"Ոչ աստղերից, այլ քո աչքերից եմ ճշմարտությունը քաղում","en":"Sonnet 14","ru":"Сонет 14"},
    "Սոնետ  15": {"hy":"Ամեն ինչ մահկանացու է, բանաստեղծությունը հավերժացնում է","en":"Sonnet 15","ru":"Сонет 15"},
    "Սոնետ  16": {"hy":"Ժամանակի դեմ ավելի լավ զենք՝ զավակը","en":"Sonnet 16","ru":"Сонет 16"},
    "Սոնետ  17": {"hy":"Իմ բանաստեղծությանը չեն հավատա, եթե զավակ չունենաս","en":"Sonnet 17","ru":"Сонет 17"},
    "Սոնետ  18": {"hy":"Համեմատություն ամառային օրվա հետ՝ հավերժություն բանաստեղծության մեջ","en":"Sonnet 18","ru":"Сонет 18"},
    "Սոնետ  19": {"hy":"Ժամանակին մարտահրավեր՝ սերը կապրի իմ տողերում","en":"Sonnet 19","ru":"Сонет 19"},
    "Սոնետ  20": {"hy":"Կրքիս տիրակալը՝ երկակի գեղեցկություն","en":"Sonnet 20","ru":"Сонет 20"},
    "Սոնետ  21": {"hy":"Իրական սեր՝ առանց չափազանցված գովասանքի","en":"Sonnet 21","ru":"Сонет 21"},
    "Սոնետ  22": {"hy":"Փոխանակված սրտեր՝ սերը ծերացնել չի թողնում","en":"Sonnet 22","ru":"Сонет 22"},
    "Սոնետ  23": {"hy":"Անկատար դերասան՝ թող հայացքն ասի սերը","en":"Sonnet 23","ru":"Сонет 23"},
    "Սոնետ  24": {"hy":"Աչքս քո պատկերը նկարել է սրտիս մեջ","en":"Sonnet 24","ru":"Сонет 24"},
    "Սոնետ  25": {"hy":"Հանգիստ սերը ավելի արժեքավոր է, քան փառքը","en":"Sonnet 25","ru":"Сонет 25"},
    "Սոնետ  26": {"hy":"Սիրո տիրակալին ուղղված հարգանք","en":"Sonnet 26","ru":"Сонет 26"},
    "Սոնետ  27": {"hy":"Հոգնած մարմին, բայց միտքը գիշերով քեզ մոտ է","en":"Sonnet 27","ru":"Сонет 27"},
    "Սոնետ  28": {"hy":"Ոչ ցերեկ, ոչ գիշեր հանգիստ չկա առանց քեզ","en":"Sonnet 28","ru":"Сонет 28"},
    "Սոնետ  29": {"hy":"Դժբախտության մեջ քո մասին մտածելը ամեն ինչ փոխում է","en":"Sonnet 29","ru":"Сонет 29"},
    "Սոնետ  30": {"hy":"Հիշողությունների տխուր նիստ, բայց քո հիշատակը բժշկում է","en":"Sonnet 30","ru":"Сонет 30"},
    "Սոնետ  31": {"hy":"Կորցրած սերերը ապրում են քո սրտում","en":"Sonnet 31","ru":"Сонет 31"},
    "Սոնետ  32": {"hy":"Իմ մահից հետո վերընթերցիր այս տողերը","en":"Sonnet 32","ru":"Сонет 32"},
    "Սոնետ  33": {"hy":"Փառավոր առավոտը՝ քո անկայունության այլաբանություն","en":"Sonnet 33","ru":"Сонет 33"},
    "Սոնետ  34": {"hy":"Խոստացած գեղեցիկ օրվա դավաճանությունը","en":"Sonnet 34","ru":"Сонет 34"},
    "Սոնետ  35": {"hy":"Մի տանջվիր քո արածի համար՝ ներում","en":"Sonnet 35","ru":"Сонет 35"},
    "Սոնետ  36": {"hy":"Երկու սեր, բայց հրապարակային ամոթի պատճառով բաժանում","en":"Sonnet 36","ru":"Сонет 36"},
    "Սոնետ  37": {"hy":"Ծերացած հայրը ուրախանում է որդու առաքինություններով","en":"Sonnet 37","ru":"Сонет 37"},
    "Սոնետ  38": {"hy":"Դու ես իմ երգի ներշնչանքը","en":"Sonnet 38","ru":"Сонет 38"},
    "Սոնետ  39": {"hy":"Ինչպե՞ս գովեմ քեզ, եթե դու իմ մասն ես","en":"Sonnet 39","ru":"Сонет 39"},
    "Սոնետ  40": {"hy":"Դու վերցրիր իմ սերը՝ դավաճանության ցավ","en":"Sonnet 40","ru":"Сонет 40"},
    "Սոնետ  41": {"hy":"Երիտասարդության թեթև մեղքերի ներում","en":"Sonnet 41","ru":"Сонет 41"},
    "Սոնետ  42": {"hy":"Սիրո եռանկյունու ցավը","en":"Sonnet 42","ru":"Сонет 42"},
    "Սոնետ  43": {"hy":"Փակ աչքերով ավելի լավ եմ տեսնում քեզ երազում","en":"Sonnet 43","ru":"Сонет 43"},
    "Սոնետ  44": {"hy":"Եթե միտքը մարմին լիներ, ակնթարթորեն քեզ մոտ կլինեի","en":"Sonnet 44","ru":"Сонет 44"},
    "Սոնետ  45": {"hy":"Օդ ու կրակ տարրերի պես մտքերս քեզ մոտ են թռչում","en":"Sonnet 45","ru":"Сонет 45"},
    "Սոնետ  46": {"hy":"Աչքի ու սրտի կռիվը քո պատկերի համար","en":"Sonnet 46","ru":"Сонет 46"},
    "Սոնետ  47": {"hy":"Աչքն ու սիրտը դաշինք են կնքում","en":"Sonnet 47","ru":"Сонет 47"},
    "Սոնետ  48": {"hy":"Վախ քեզ կորցնելուց, թեև սիրտս քեզ ապահով է պահում","en":"Sonnet 48","ru":"Сонет 48"},
    "Սոնետ  49": {"hy":"Նախապատրաստվում եմ այն օրվան, երբ կհրաժարվես ինձնից","en":"Sonnet 49","ru":"Сонет 49"},
    "Սոնետ  50": {"hy":"Տխուր ճամփորդություն՝ հեռանալով քեզնից","en":"Sonnet 50","ru":"Сонет 50"},
    "Սոնետ  51": {"hy":"Դանդաղ գնալու արդարացումը, արագ վերադարձի փափագը","en":"Sonnet 51","ru":"Сонет 51"},
    "Սոնետ  52": {"hy":"Հազվադեպ հանդիպումները՝ գանձի պես սպասված","en":"Sonnet 52","ru":"Сонет 52"},
    "Սոնետ  53": {"hy":"Քո գեղեցկությունը գերազանցում է բոլոր ստվերներին","en":"Sonnet 53","ru":"Сонет 53"},
    "Սոնետ  54": {"hy":"Ճշմարտությունը գեղեցկությանը տալիս է հավերժական բույր","en":"Sonnet 54","ru":"Сонет 54"},
    "Սոնետ  55": {"hy":"Բանաստեղծությունը գերազանցում է մարմարե հուշարձաններին","en":"Sonnet 55","ru":"Сонет 55"},
    "Սոնետ  56": {"hy":"Նորոգիր սերդ, որ չմաշվի կրկնությունից","en":"Sonnet 56","ru":"Сонет 56"},
    "Սոնետ  57": {"hy":"Հավատարիմ ծառայությունը՝ սպասում առանց հարցականի","en":"Sonnet 57","ru":"Сонет 57"},
    "Սոնետ  58": {"hy":"Համբերությունը՝ քո ազատության հանդեպ հարգանք","en":"Sonnet 58","ru":"Сонет 58"},
    "Սոնետ  59": {"hy":"Միգուցե անցյալի բանաստեղծներն արդեն նկարագրել են այս գեղեցկությունը","en":"Sonnet 59","ru":"Сонет 59"},
    "Սոնետ  60": {"hy":"Ժամանակը կուլ է տալիս երիտասարդությունը, միայն տողերն են դիմադրում","en":"Sonnet 60","ru":"Сонет 60"},
    "Սոնետ  61": {"hy":"Անքնություն և թախիծ՝ սիրելիի կերպարից բաժանված","en":"Sonnet 61","ru":"Сонет 61"},
    "Սոնետ  62": {"hy":"Ինքնասիրությունը վերափոխվում է սիրելիի հանդեպ սերի","en":"Sonnet 62","ru":"Сонет 62"},
    "Սոնետ  63": {"hy":"Ժամանակի դեմ պայքար՝ գեղեցկությունը հավերժացնել բանաստեղծության մեջ","en":"Sonnet 63","ru":"Сонет 63"},
    "Սոնետ  64": {"hy":"Ժամանակի ավերիչ ուժը՝ վախ կորցնելու սիրելիին","en":"Sonnet 64","ru":"Сонет 64"},
    "Սոնետ  65": {"hy":"Միայն բանաստեղծության թանաքի մեջ կարող է գեղեցկությունը հաղթել ժամանակին","en":"Sonnet 65","ru":"Сонет 65"},
    "Սոնետ  66": {"hy":"Աշխարհի անարդարություններից հոգնածություն, բայց սերը պահում է կյանքին","en":"Sonnet 66","ru":"Сонет 66"},
    "Սոնետ  67": {"hy":"Ինչու գեղեցկությունը պետք է ապրի ապականված աշխարհում","en":"Sonnet 67","ru":"Сонет 67"},
    "Սոնետ  68": {"hy":"Նրա դեմքը՝ հին, անկեղծ գեղեցկության քարտեզ, առանց արհեստականության","en":"Sonnet 68","ru":"Сонет 68"},
    "Սոնետ  69": {"hy":"Արտաքին գեղեցկությունը գովում են բոլորը, բայց հոգու գեղեցկությունը կասկածի տակ","en":"Sonnet 69","ru":"Сонет 69"},
    "Սոնետ  70": {"hy":"Զրպարտությունը հարվածում է լավագույններին, մեղադրանքը դեռ մեղք չի նշանակում","en":"Sonnet 70","ru":"Сонет 70"},
    "Սոնետ  71": {"hy":"Մի սգա ինձ մահից հետո, մոռացիր ինձ","en":"Sonnet 71","ru":"Сонет 71"},
    "Սոնետ  72": {"hy":"Մի գովաբանիր ինձ ավելին, քան արժանի եմ, մահից հետո","en":"Sonnet 72","ru":"Сонет 72"},
    "Սոնետ  73": {"hy":"Աշնան տերևների այլաբանությունը՝ սերն ուժեղանում է վերջի մոտենալուն զուգահեռ","en":"Sonnet 73","ru":"Сонет 73"},
    "Սոնետ  74": {"hy":"Մահից հետո բանաստեղծությունը կպահի հոգու լավագույն մասը","en":"Sonnet 74","ru":"Сонет 74"},
    "Սոնետ  75": {"hy":"Դու ինձ համար կենսական ես, ինչպես հացը մարմնի համար","en":"Sonnet 75","ru":"Сонет 75"},
    "Սոնետ  76": {"hy":"Ինչու՞ իմ բանաստեղծություններն միշտ նույնն են՝ միշտ քեզ մասին են","en":"Sonnet 76","ru":"Сонет 76"},
    "Սոնետ  77": {"hy":"Հայելի, ժամացույց, գիրք՝ ժամանակի ու հիշողության մասին խորհրդածություն","en":"Sonnet 77","ru":"Сонет 77"},
    "Սոնետ  78": {"hy":"Ուրիշ բանաստեղծներն էլ արդեն ներշնչված են քեզնից","en":"Sonnet 78","ru":"Сонет 78"},
    "Սոնետ  79": {"hy":"Մրցակից բանաստեղծը վերցրել է իմ տեղը, բայց միայն քո գեղեցկությունն է վերադարձնում","en":"Sonnet 79","ru":"Сонет 79"},
    "Սոնետ  80": {"hy":"Մրցակից բանաստեղծի հանդեպ նախանձ և իր խոսքի աննշանության զգացում","en":"Sonnet 80","ru":"Сонет 80"},
    "Սոնետ  81": {"hy":"Իմ տողերը հավերժացնելու են քեզ, նույնիսկ եթե ես մոռացվեմ","en":"Sonnet 81","ru":"Сонет 81"},
    "Սոնետ  82": {"hy":"Դու կարող ես թարմ գովասանք փնտրել այլ գրողներից","en":"Sonnet 82","ru":"Сонет 82"},
    "Սոնետ  83": {"hy":"Չեմ նկարագրել քեզ, քանի որ խոսքերը չեն հասնում իրական գեղեցկությանը","en":"Sonnet 83","ru":"Сонет 83"},
    "Սոնետ  84": {"hy":"Ամենապարզ ճշմարտությունը՝ դու հենց դու ես","en":"Sonnet 84","ru":"Сонет 84"},
    "Սոնետ  85": {"hy":"Իմ լուռ մուսան լռում է, մինչ ուրիշներն բարձրաձայն են գովում քեզ","en":"Sonnet 85","ru":"Сонет 85"},
    "Սոնետ  86": {"hy":"Մրցակից բանաստեղծի հզոր տողերն էին, որ ինձ լռեցրին","en":"Sonnet 86","ru":"Сонет 86"},
    "Սոնետ  87": {"hy":"Հրաժեշտ՝ դու չափազանց թանկ ես, որ ինձ պատկանես","en":"Sonnet 87","ru":"Сонет 87"},
    "Սոնետ  88": {"hy":"Եթե լքես ինձ, ես ինքս կկանգնեմ քո կողմից","en":"Sonnet 88","ru":"Сонет 88"},
    "Սոնետ  89": {"hy":"Կընդունեմ քո հորինած մեղքը, որ արդարացնեմ հեռանալդ","en":"Sonnet 89","ru":"Сонет 89"},
    "Սոնետ  90": {"hy":"Խնդրանք՝ եթե պիտի լքես, արա հիմա, երբ ցավերն արդեն շատ են","en":"Sonnet 90","ru":"Сонет 90"},
    "Սոնետ  91": {"hy":"Ոմանք հպարտանում են ծագումով, հարստությամբ, ես՝ քո սիրով","en":"Sonnet 91","ru":"Сонет 91"},
    "Սոնետ  92": {"hy":"Նույնիսկ եթե լքես ինձ, կյանքս կավարտվի քո սիրո հետ, ուստի ոչնչից չեմ վախենում","en":"Sonnet 92","ru":"Сонет 92"},
    "Սոնետ  93": {"hy":"Կապրեմ հավատալով քո սիրուն, թեև հայացքդ կարող է խաբուսիկ լինել","en":"Sonnet 93","ru":"Сонет 93"},
    "Սոնետ 94": {"hy":"Ուժ ունեցողները, ովքեր չարիք չեն գործում՝ ինքնատիրապետման գովքը","en":"Sonnet 94","ru":"Сонет 94"},
    "Սոնետ  95": {"hy":"Որքան քաղցր ես քողարկում մեղքերդ գեղեցկությամբդ","en":"Sonnet 95","ru":"Сонет 95"},
    "Սոնետ  96": {"hy":"Ոմանք երիտասարդության քո անառակությունն են տեսնում, ուրիշները՝ հմայք","en":"Sonnet 96","ru":"Сонет 96"},
    "Սոնետ  97": {"hy":"Հեռավորությունը քեզնից ձմեռվա պես էր զգացվում, թեև ամառ էր","en":"Sonnet 97","ru":"Сонет 97"},
    "Սոնետ  98": {"hy":"Գարունը առանց քեզ ձմեռվա պես թվաց, չնայած ծաղիկների","en":"Sonnet 98","ru":"Сонет 98"},
    "Սոնետ  99": {"hy":"Մանուշակին մեղադրում եմ, որ քո հոտն ու գույնն է գողացել","en":"Sonnet 99","ru":"Сонет 99"},
    "Սոնետ  100": {"hy":"Մուսա, որտե՞ղ էիր, վերադարձի՛ր ու երգի՛ր նորից","en":"Sonnet 100","ru":"Сонет 100"},
    "Սոնետ  101": {"hy":"Ճշմարտությունն ու գեղեցկությունը զարդարանք չեն պահանջում","en":"Sonnet 101","ru":"Сонет 101"},
    "Սոնետ  102": {"hy":"Իմ սերն ավելի ուժեղ է, թեև ավելի քիչ եմ ցույց տալիս","en":"Sonnet 102","ru":"Сонет 102"},
    "Սոնետ  103": {"hy":"Իմ խեղճ տողերը չեն կարող արժանավայել նկարագրել քո արտացոլանքը","en":"Sonnet 103","ru":"Сонет 103"},
    "Սոնետ  104": {"hy":"Ինձ համար դու հավերժ երիտասարդ ես, թեև երեք տարի է անցել","en":"Sonnet 104","ru":"Сонет 104"},
    "Սոնետ  105": {"hy":"Իմ սերը կռապաշտություն չէ. «գեղեցիկ, բարի և ճշմարիտ» է իմ մշտական թեման","en":"Sonnet 105","ru":"Сонет 105"},
    "Սոնետ  106": {"hy":"Հին բանաստեղծների նկարագրած գեղեցկությունը քո մարգարեությունն էր","en":"Sonnet 106","ru":"Сонет 106"},
    "Սոնետ  107": {"hy":"Մահկանացության վախերն սխալ էին. սերն ու տողերն կգերազանցեն ամեն հուշարձան","en":"Sonnet 107","ru":"Сонет 107"},
    "Սոնետ  108": {"hy":"Ասելիք նոր բան չկա, բայց ինչպես աղոթքը՝ կրկնում եմ հավերժական ճշմարտությունը","en":"Sonnet 108","ru":"Сонет 108"},
    "Սոնետ  109": {"hy":"Երբեք մի ասա, թե ես կեղծ էի, թեև թվում էր, թե հեռացել եմ","en":"Sonnet 109","ru":"Сонет 109"},
    "Սոնետ  110": {"hy":"Զղջում եմ իմ սխալների համար, բայց դու մնում ես լավագույն սերս","en":"Sonnet 110","ru":"Сонет 110"},
    "Սոնետ  111": {"hy":"Մեղադրիր բախտին, ոչ թե ինձ, հրապարակային ամոթի համար","en":"Sonnet 111","ru":"Сонет 111"},
    "Սոնետ  112": {"hy":"Քո սերն ու կարեկցանքը լցնում են ուրիշների կարծիքի թողած սպիները","en":"Sonnet 112","ru":"Сонет 112"},
    "Սոնետ  113": {"hy":"Քեզնից հեռանալուց ի վեր՝ ամեն ինչ, ինչ տեսնում եմ, դառնում է քո պատկերը","en":"Sonnet 113","ru":"Сонет 113"},
    "Սոնետ  114": {"hy":"Սերս խաբու՞մ է միտքս, թե՞ իրական ալքիմիա է ստեղծում ընկալման մեջ","en":"Sonnet 114","ru":"Сонет 114"},
    "Սոնետ  115": {"hy":"Սերն անընդհատ աճում է, նույնիսկ երբ կարծես թե անհնար է ավելի մեծանալ","en":"Sonnet 115","ru":"Сонет 115"},
    "Սոնետ  116": {"hy":"Ճշմարիտ մտքերի ամուսնությունը՝ սերն անփոփոխ է ու հավերժական","en":"Sonnet 116","ru":"Сонет 116"},
    "Սոնետ  117": {"hy":"Մեղադրիր ինձ անուշադրության մեջ, բայց ես երբեք չեմ դադարել սիրել","en":"Sonnet 117","ru":"Сонет 117"},
    "Սոնետ  118": {"hy":"Ինչպես դառը համը սրում է ախորժակը, փորձեցի բազմազանություն ու հիվանդացա","en":"Sonnet 118","ru":"Сонет 118"},
    "Սոնետ  119": {"hy":"Սխալներս սերն ավելի ուժեղ դարձրին հետո","en":"Sonnet 119","ru":"Сонет 119"},
    "Սոնետ  120": {"hy":"Այն, որ դու մի ժամանակ դաժան էիր, օգնում է ինձ հիմա հանդուրժել քո դաժանությունը","en":"Sonnet 120","ru":"Сонет 120"},
    "Սոնետ  121": {"hy":"Ավելի լավ է վատը լինել, քան անարդար դատապարտվել","en":"Sonnet 121","ru":"Сонет 121"},
    "Սոնետ  122": {"hy":"Քո նվերը հիշողությանս մեջ է, ֆիզիկական գրառում պետք չէ","en":"Sonnet 122","ru":"Сонет 122"},
    "Սոնետ  123": {"hy":"Ժամանակ, դու չես կարող պարծենալ, թե փոխվում եմ, ես ճշմարիտ եմ մնում","en":"Sonnet 123","ru":"Сонет 123"},
    "Սոնետ  124": {"hy":"Եթե սերս պետության զավակ լիներ, կարող էր արմատախիլ լինել, բայց չէ","en":"Sonnet 124","ru":"Сонет 124"},
    "Սոնետ  125": {"hy":"Ինձ արտաքին ցուցադրում պետք չէ, միայն փոխադարձ անկեղծություն","en":"Sonnet 125","ru":"Сонет 125"},
    "Սոնետ  126": {"hy":"Բնության հսկիչը վերջում պիտի հանձնի պատանուն Ժամանակին","en":"Sonnet 126","ru":"Сонет 126"},
    "Սոնետ  127": {"hy":"Սևը այժմ գեղեցիկ է համարվում, մուգ գեղեցկությունը վերասահմանում է չափանիշները","en":"Sonnet 127","ru":"Сонет 127"},
    "Սոնետ  128": {"hy":"Խանդ՝ դաշնամուրի ստեղների նկատմամբ, որոնց դիպչում է սիրելին","en":"Sonnet 128","ru":"Сонет 128"},
    "Սոնետ  129": {"hy":"Ցանկության վատնումը ամոթի մեջ՝ կրքի դատապարտումը որպես խելագարություն","en":"Sonnet 129","ru":"Сонет 129"},
    "Սոնետ  130": {"hy":"Իմ սիրելիի աչքերը արևի նման չեն. իրատեսական, ոչ իդեալականացված սեր","en":"Sonnet 130","ru":"Сонет 130"},
    "Սոնետ  131": {"hy":"Սիրելին բռնակալի պես իշխում է սրտի վրա, թեև ուրիշների աչքում գեղեցիկ չէ","en":"Sonnet 131","ru":"Сонет 131"},
    "Սոնետ  132": {"hy":"Նրա աչքերը սևով սգում են նրա համար, մաղթում է, որ սիրտն էլ սգար","en":"Sonnet 132","ru":"Сонет 132"},
    "Սոնետ  133": {"hy":"Անեծք այն սրտին, որ վիրավորում է թե՛ ինձ, թե՛ ընկերոջս","en":"Sonnet 133","ru":"Сонет 133"},
    "Սոնետ  134": {"hy":"Իրավական այլաբանություն՝ ինքս ինձ գրավ եմ դրել՝ ընկերոջս պահելու համար","en":"Sonnet 134","ru":"Сонет 134"},
    "Սոնետ  135": {"hy":"Բառախաղ «կամք» բառի շուրջ՝ աղերսանք ցանկության համար","en":"Sonnet 135","ru":"Сонет 135"},
    "Սոնետ  136": {"hy":"Էլի բառախաղ «կամքի» շուրջ՝ եղիր մեկը նրա բազում ցանկություններից","en":"Sonnet 136","ru":"Сонет 136"},
    "Սոնետ  137": {"hy":"Կույր Սերն իմ աչքերին սխալ դատողության տարավ","en":"Sonnet 137","ru":"Сонет 137"},
    "Սոնետ  138": {"hy":"Երբ սիրելիս երդվում է, թե ճշմարտությունից է կերտված՝ փոխադարձ քաղցր սուտը պահպանում է սերը","en":"Sonnet 138","ru":"Сонет 138"},
    "Սոնետ  139": {"hy":"Խնդրում եմ՝ մի արդարացրու սխալներդ, այլ սպանիր ինձ աչքերովդ, ոչ խորամանկությամբ","en":"Sonnet 139","ru":"Сонет 139"},
    "Սոնետ  140": {"hy":"Զգուշացնում եմ քեզ. ձևացրու, թե սիրում ես, թե չես կարող իրապես","en":"Sonnet 140","ru":"Сонет 140"},
    "Սոնետ  141": {"hy":"Սիրում եմ նրան հակառակ բանականության՝ զգայարանքներս սրտից են հաղթված","en":"Sonnet 141","ru":"Сонет 141"},
    "Սոնետ  142": {"hy":"Սերս մեղք է, նրա առաքինությունը՝ իմ սերն ատելը, մինչդեռ ինքն էլ է անհավատարիմ","en":"Sonnet 142","ru":"Сонет 142"},
    "Սոնետ  143": {"hy":"Տնային տնտեսուհին հավին հետապնդում է՝ մոռանալով լացող երեխային, ինչպես ինձ մոռանում է","en":"Sonnet 143","ru":"Сонет 143"},
    "Սոնետ  144": {"hy":"Երկու սեր՝ գեղեցիկ տղամարդ ու մուգ կին, վախենում եմ, որ նա ապականել է հրեշտակիս","en":"Sonnet 144","ru":"Сонет 144"},
    "Սոնետ  145": {"hy":"Բառախաղ. «ատում եմ» դարձավ «ոչ քեզ» ու փրկեց հուսահատությունից","en":"Sonnet 145","ru":"Сонет 145"},
    "Սոնետ  146": {"hy":"Խեղճ հոգի, մարմնիս մեղավոր հողի կենտրոնում՝ հոգևոր խորհրդածություն","en":"Sonnet 146","ru":"Сонет 146"},
    "Սոնետ  147": {"hy":"Սերն ինչպես տենդ է՝ բանականությունը լքված է, հուսահատ ու խելագար","en":"Sonnet 147","ru":"Сонет 147"},
    "Սոնետ  148": {"hy":"Ինչպիսի՞ աչքեր է սերը դրել գլխիս մեջ՝ սերը կուրացնում է դատողությունը","en":"Sonnet 148","ru":"Сонет 148"},
    "Սոնետ  149": {"hy":"Մեղադրում եմ նրան, թե չի սիրում ինձ, եթե չի ատում այն, ինչ ես եմ ատում","en":"Sonnet 149","ru":"Сонет 149"},
    "Սոնետ  150": {"hy":"Ի՞նչ զորություն ունի նա, որ ինձ ավելի է սիրեցնում, որքան շատ եմ տեսնում նրա թերությունները","en":"Sonnet 150","ru":"Сонет 150"},
    "Սոնետ  151": {"hy":"Սերն ու խիղճը կոնֆլիկտի մեջ են՝ մարմինն ու հոգին պատռված են կրքից","en":"Sonnet 151","ru":"Сонет 151"},
    "Սոնետ  152": {"hy":"Ես երդվել եմ սիրել նրան, նա՝ ուրիշներին. փոխադարձ երդման խախտում","en":"Sonnet 152","ru":"Сонет 152"},
    "Սոնետ  153": {"hy":"Կուպիդոնի հեքիաթային ջահը՝ սիրո տենդի այլաբանություն","en":"Sonnet 153","ru":"Сонет 153"},
    "Սոնետ  154": {"hy":"Նույն առասպելը՝ Կուպիդոնի ջահը մարում է, բայց սերը ջրով չի հովանում","en":"Sonnet 154","ru":"Сонет 154"},
    "vahan-teryan/ananun ser": {"en":"Nameless Love","ru":"Безымянная любовь"},
    "vahan-teryan/ashnan erg": {"en":"Autumn Song","ru":"Осенняя песня"},
    "vahan-teryan/Աշուն Է անձրև": {"en":"Autumn, Rain","ru":"Осень, дождь"},
    "vahan-teryan/es chgitem ur en tanum heravor": {"en":"I Don't Know Where the Distant Roads Lead","ru":"Я не знаю, куда ведут далёкие"},
    "vahan-teryan/es sirum em qo meravor achqery xor": {"en":"I Love Your Deep, Guilty Eyes","ru":"Люблю твои глубокие, грешные глаза"},
    "vahan-teryan/elegia": {"en":"Elegy","ru":"Элегия"},
    "vahan-teryan/estonakan": {"en":"Estonian Song","ru":"Эстонская"},
    "vahan-teryan/im xarar erekon e hima": {"en":"My Quiet Evening Is Now","ru":"Мой тихий вечер сейчас"},
    "vahan-teryan/iriknajam": {"en":"Evening Hour","ru":"Вечерний час"},
    "vahan-teryan/xarar gisherov du kgas inz mot": {"en":"You'll Come to Me on a Quiet Night","ru":"Ты придёшь ко мне тихой ночью"},
    "vahan-teryan/xosqery vchit en u xorunk": {"en":"The Words Are Clear and Deep","ru":"Слова ясны и глубоки"},
    "vahan-teryan/Կարոտ": {"en":"Longing","ru":"Тоска"},
    "vahan-teryan/hrajeshti gazel": {"en":"Farewell Ghazal","ru":"Прощальная газель"},
    "vahan-teryan/hrashk argik": {"en":"Miracle Girl","ru":"Чудо-девушка"},
    "vahan-teryan/mtnshar": {"en":"Twilight","ru":"Сумерки"},
    "vahan-teryan/Մոռանալ": {"en":"To Forget","ru":"Забыть"},
    "vahan-teryan/sentimental erg": {"en":"Sentimental Song","ru":"Сентиментальная песня"},
    "vahan-teryan/sev gisher e noric u husher anhamar": {"en":"Black Night Again, Countless Memories","ru":"Снова чёрная ночь, без счёта воспоминаний"},
    "vahan-teryan/qo achqeri dem im achqery kujr": {"en":"Before Your Eyes, My Eyes Are Blind","ru":"Перед твоими глазами мои глаза слепы"},
    "vahan-teryan/Autumn and Rain  Աշուն Է անձրև": {"ru":"Осень и дождь"},
    "vahan-teryan/Golden Stars in Blue(Տխուր զրույց)": {"ru":"Золотые звёзды в синеве"},
    "hamo-sahyan/axr es inchpes ver kenam gnam": {"en":"How Can I Rise and Leave","ru":"Как же мне встать и уйти"},
    "hamo-sahyan/amen aravot": {"en":"Every Morning","ru":"Каждое утро"},
    "hamo-sahyan/Ամպ է Նորից": {"en":"Cloudy Again","ru":"Снова облачно"},
    "hamo-sahyan/anzrev": {"en":"Rain","ru":"Дождь"},
    "hamo-sahyan/anund talis": {"en":"Saying Your Name","ru":"Произнося твоё имя"},
    "hamo-sahyan/arajin ser": {"en":"My First Love","ru":"Моя первая любовь"},
    "hamo-sahyan/guce henc ajster": {"en":"Maybe Right Here","ru":"Может, именно здесь"},
    "hamo-sahyan/du inz torel eir menak": {"en":"You Had Left Me Alone","ru":"Ты оставила меня одного"},
    "hamo-sahyan/duq lavn eq mardiq": {"en":"You Are Good, People","ru":"Вы хорошие, люди"},
    "hamo-sahyan/es kuzei ": {"en":"I Would Like","ru":"Я хотел бы"},
    "hamo-sahyan/es chem karogh chnershnchvel": {"en":"I Cannot Help Being Inspired","ru":"Я не могу не вдохновляться"},
    "hamo-sahyan/es chem karogh chnershnchvel roc": {"en":"I Cannot Help Being Inspired (Rock)","ru":"Я не могу не вдохновляться (рок)"},
    "hamo-sahyan/es u du": {"en":"You and I","ru":"Я и ты"},
    "hamo-sahyan/ev chimacanq te inchu": {"en":"And We Never Knew Why","ru":"И мы не узнали, почему"},
    "hamo-sahyan/torvochvoqi chkanchen": {"en":"Let No One Be Summoned","ru":"Пусть никого не зовут"},
    "hamo-sahyan/tor vochvoqi chkanchen02roc": {"en":"Let No One Be Called (Rock)","ru":"Пусть никого не зовут (рок)"},
    "hamo-sahyan/torvochvoqi chkanchen roc": {"en":"Let No One Be Summoned (Rock)","ru":"Пусть никого не зовут (рок)"},
    "hamo-sahyan/inch anem mairik": {"en":"What Should I Do, Mother","ru":"Что мне делать, мама"},
    "hamo-sahyan/inch taqcnem": {"en":"What Should I Hide","ru":"Что мне скрывать"},
    "hamo-sahyan/inch arac mard em": {"en":"What Can I Do, I'm Human","ru":"Что поделать, я человек"},
    "hamo-sahyan/inchu hishecri": {"en":"Why Did You Remind Me","ru":"Зачем ты напомнил"},
    "hamo-sahyan/covn er gisher er es ei u du": {"en":"It Was the Sea, the Night, You and I","ru":"Было море, была ночь, были я и ты"},
    "hamo-sahyan/ka mi tulutun": {"en":"There Is a Weakness","ru":"Есть слабость"},
    "hamo-sahyan/kanch": {"en":"Call","ru":"Зов"},
    "hamo-sahyan/kgam": {"en":"I Will Come","ru":"Я приду"},
    "hamo-sahyan/hajastan aselis": {"en":"When Saying \"Armenia\"","ru":"Когда произношу «Армения»"},
    "hamo-sahyan/hajastan aselis roc": {"en":"When Saying \"Armenia\" (Rock)","ru":"Когда произношу «Армения» (рок)"},
    "hamo-sahyan/hognel em": {"en":"I'm Tired","ru":"Я устал"},
    "hamo-sahyan/horovely": {"en":"The Plowing Song","ru":"Пахотная песня"},
    "hamo-sahyan/mer lezun": {"en":"Our Language","ru":"Наш язык"},
    "hamo-sahyan/mitegh ishxan u ter": {"en":"Somewhere a Prince and Lord","ru":"Где-то князь и господин"},
    "hamo-sahyan/mijocners": {"en":"My Means","ru":"Мои средства"},
    "hamo-sahyan/vochinch chi poxvi": {"en":"Nothing Will Change","ru":"Ничего не изменится"},
    "hamo-sahyan/um hamar im ushqy gnac": {"en":"For Whom My Mind Was Lost","ru":"Ради кого я потерял разум"},
    "hamo-sahyan/ches asi voch mi barov": {"en":"You Won't Say a Kind Word","ru":"Ты не скажешь доброго слова"},
    "hamo-sahyan/papy": {"en":"Grandfather","ru":"Дедушка"},
    "hamo-sahyan/vshtacel em amen inchic": {"en":"I've Grieved Over Everything","ru":"Я опечалился всем"},
    "hamo-sahyan/tar inz jamanak": {"en":"Carry Me Away, Time","ru":"Увези меня, время"},
    "hamo-sahyan/tar inz jamanak roc": {"en":"Carry Me Away, Time (Rock)","ru":"Увези меня, время (рок)"},
    "hamo-sahyan/Փնտրում ես դու": {"en":"You Are Searching","ru":"Ты ищешь"},
    "hamo-sahyan/qamu hamburic": {"en":"From the Kiss of the Wind","ru":"От поцелуя ветра"},
    "hamo-sahyan/How Can I Just Leave": {"hy":"Ինչպե՞ս գնամ","ru":"Как же мне уйти"},
    "hamo-sahyan/I Will Come Anyway": {"hy":"Միևնույն է՝ կգամ","ru":"Всё равно я приду"},
    "hamo-sahyan/My First Love": {"hy":"Իմ առաջին սերը","ru":"Первая любовь моя"},
    "hamo-sahyan/Our Language": {"hy":"Մեր լեզուն","ru":"Наш язык"},
    "hamo-sahyan/The Forest's Whisper": {"hy":"Անտառի շշունջը","ru":"Шёпот леса"},
    "hamo-sahyan/The One in Vain": {"hy":"Զուրն է","ru":"Напрасно"},
    "hamo-sahyan/The Thunderstorm": {"hy":"Ամպրոպը","ru":"Гроза"},
    "hamo-sahyan/vsio ravno pridu": {"hy":"Միևնույն է՝ կգամ","en":"I Will Come Anyway"},
    "hamo-sahyan/vsem kem ya bil": {"hy":"Այն ամենը, ինչ ես եղել եմ","en":"All That I Have Been"},
    "hamo-sahyan/dojd": {"hy":"Անձրև","en":"Rain"},
    "hamo-sahyan/dojd roc": {"hy":"Անձրև (ռոք)","en":"Rain (Rock)"},
    "hamo-sahyan/kak je mne uyti": {"hy":"Ինչպե՞ս գնամ","en":"How Can I Just Leave"},
    "hamo-sahyan/mama": {"hy":"Մայրիկ","en":"Mama"},
    "hamo-sahyan/moi sredstva moi zaboti": {"hy":"Իմ միջոցները... Իմ հոգսերը...","en":"My Means... My Worries..."},
    "hamo-sahyan/moya neprojitaya jizn": {"hy":"Իմ չապրված կյանքը","en":"My Unlived Life"},
    "hamo-sahyan/nash yazik": {"hy":"Մեր լեզուն","en":"Our Language"},
    "hamo-sahyan/pervaya lubov": {"hy":"Իմ առաջին սերը","en":"My First Love"},
    "hamo-sahyan/paceluy vetra": {"hy":"Քամու համբույրը","en":"The Wind's Kiss"},
    "hamo-sahyan/proshay": {"hy":"Հրաժեշտ","en":"Farewell"},
    "hamo-sahyan/uznat menya ne tak prosto": {"hy":"Ինձ ճանաչելը հեշտ չէ","en":"It's Not So Easy to Know Me"},
    "hamo-sahyan/chto bilo to bilo": {"hy":"Ինչ եղել է, եղել է","en":"What Was, Was"},
    "hamo-sahyan/ya xotel razdeliat": {"hy":"Ես կցանկանայի կիսել քեզ հետ","en":"I Wished to Share with You"},
    "hamo-sahyan/Հայոց փշատենին": {"en":"The Armenian Oleaster","ru":"Армянская джида"},
    "hamo-sahyan/Հայոց փշատենին ջազ": {"en":"The Armenian Oleaster (Jazz)","ru":"Армянская джида (джаз)"},
    "parujr-sevak/erku siro aranqum": {"en":"Between Two Loves","ru":"Между двумя любовями"},
    "parujr-sevak/erku siro aranqum roc": {"en":"Between Two Loves (Rock)","ru":"Между двумя любовями (рок)"},
    "parujr-sevak/menq qich enq sakajn mez haj en asum": {"en":"We Are Few, But They Call Us Armenians","ru":"Нас мало, но нас зовут армянами"},
    "parujr-sevak/miangamic roc": {"en":"All at Once (Rock)","ru":"Сразу (рок)"},
    "parujr-sevak/miangamic tango": {"en":"All at Once (Tango)","ru":"Сразу (танго)"},
    "parujr-sevak/Նախանձում եմ": {"en":"I Envy","ru":"Я завидую"},
    "parujr-sevak/ՍԵՐՆ ԻՆՉ ԳՈՒՅՆ ՈՒՆԻ": {"en":"What Color Is Love","ru":"Какого цвета любовь"},
    "parujr-sevak/What Color Is Love": {"hy":"Սերն ինչ գույն ունի","ru":"Какого цвета любовь"},
    "parujr-sevak/Какого цвета любовь": {"hy":"Սերն ինչ գույն ունի","en":"What Color Is Love"},
    "avetik-isahakyan/Ախ կուզես լինիմ": {"en":"Ah, If Only I Could Be","ru":"Ах, хотел бы я быть"},
    "aramayis-sahakyan/Ես կուզեի քո ճանապարհին": {"en":"I Wished to Be on Your Path","ru":"Я хотел бы быть на твоём пути"},
    "shiraz/Իմ պատանի սիրտս": {"en":"My Youthful Heart","ru":"Моё юное сердце"},
    "silva-kaputikyan/Լուսինն ու Արևը": {"en":"The Moon and the Sun","ru":"Луна и Солнце"},
    "silva-kaputikyan/Ծուխը չերևա": {"en":"Let No Smoke Show","ru":"Чтоб дыма не было видно"},
    "silva-kaputikyan/Ոչ մեր սիրելն էր նման սիրելու": {"en":"Our Love Was Not Like Any Other","ru":"Наша любовь была не такой"},
    "silva-kaputikyan/Սեր": {"en":"Love","ru":"Любовь"},
    "silva-kaputikyan/Քեզ փնտրում եմ": {"en":"I'm Searching for You","ru":"Я ищу тебя"},
    "silva-kaputikyan/The Moons Jealousy": {"hy":"Լուսինն ու Արևը","ru":"Белая Луна"},
    "silva-kaputikyan/Белая Луна": {"hy":"Լուսինն ու Արևը","en":"The Moon's Jealousy"},
    "vahagn-davtyan/Սեր": {"en":"Love","ru":"Любовь"},
    "hovhannes-tumanyan/Սիրում էի երբեմն քեզ": {"en":"I Once Loved You","ru":"Я когда-то любил тебя"},
    "shiraz/Սիրո համար մահ չկա": {"en":"For Love, There Is No Death","ru":"Ради любви нет смерти"},
    "shiraz/Հայոց լեզուն": {"en":"The Armenian Language","ru":"Армянский язык"},
    "shiraz/Սիրո հիասթափություն": {"en":"Disillusionment in Love","ru":"Разочарование в любви"},
    "shiraz/Իմ Սուրբ Հայրենիք": {"en":"My Holy Homeland","ru":"Моя святая Родина"},
    "shiraz/Դու իմ միակ աստվածուհի": {"en":"You Are My Only Goddess","ru":"Ты моя единственная богиня"},
    "shiraz/Դու էլ ի՛մն ես": {"en":"You Are Mine Too","ru":"Ты тоже моя"}
  },
  sources: {
    "imastun|Meghki_ezrin_Remix": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/imastun/featured/meghki_ezrin_Remix.mp3",
    "imastun|Նախանձում եմ": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/imastun/featured/mascito/%D5%86%D5%A1%D5%AD%D5%A1%D5%B6%D5%B1%D5%B8%D6%82%D5%B4%20%D5%A5%D5%B4.mp3",
    "imastun|Ջրահարսեր Ремикс Ремикс_2": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/mer-jraharsere/featured/%D5%8B%D6%80%D5%A1%D5%B0%D5%A1%D6%80%D5%BD%D5%A5%D6%80%20%D0%A0%D0%B5%D0%BC%D0%B8%D0%BA%D1%81%20%D0%A0%D0%B5%D0%BC%D0%B8%D0%BA%D1%81_2.mp3",
    "imastun|Ջրահարսեր Ремикс Ремикс_3": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/mer-jraharsere/featured/%D5%8B%D6%80%D5%A1%D5%B0%D5%A1%D6%80%D5%BD%D5%A5%D6%80%20%D0%A0%D0%B5%D0%BC%D0%B8%D0%BA%D1%81%20%D0%A0%D0%B5%D0%BC%D0%B8%D0%BA%D1%81_3.mp3",
    "imastun|IM JEALOUS OF THE MOSQUITO": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/imastun/featured/mascito/IM%20JEALOUS%20OF%20THE%20MOSQUITO.mp3",
    "imastun|Our Lovely Mermaids": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/mer-jraharsere/featured/Our%20Lovely%20Mermaids.mp3",
    "imastun|Ревую к комару": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/imastun/featured/mascito/%D0%A0%D0%B5%D0%B2%D1%83%D1%8E%20%D0%BA%20%D0%BA%D0%BE%D0%BC%D0%B0%D1%80%D1%83.mp3",
    "imastun|Эй наши русалки": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/mer-jraharsere/featured/%D0%AD%D0%B9%20%D0%BD%D0%B0%D1%88%D0%B8%20%D1%80%D1%83%D1%81%D0%B0%D0%BB%D0%BA%D0%B8.mp3",
    "imastun|ჩვენი ქალთევზებო": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/mer-jraharsere/featured/%E1%83%A9%E1%83%95%E1%83%94%E1%83%9C%E1%83%98%20%E1%83%A5%E1%83%90%E1%83%9A%E1%83%97%E1%83%94%E1%83%95%E1%83%96%E1%83%94%E1%83%91%E1%83%9D.mp3",
    "go-hara|Անունդ կին է ֆրի տանգո": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/go-hara/featured/%D4%B1%D5%B6%D5%B8%D6%82%D5%B6%D5%A4%20%D5%AF%D5%AB%D5%B6%20%D5%A7.mp3",
    "haj-poetner|hamo-sahyan/Հայոց փշատենին ջազ": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/haj-poetner/featured/hamo-sahyan%2F%D5%80%D5%A1%D5%B5%D5%B8%D6%81%20%D6%83%D5%B7%D5%A1%D5%BF%D5%A5%D5%B6%D5%AB%D5%B6%20jazz.mp3",
    "haj-poetner|shiraz/Սիրո համար մահ չկա": "https://pub-2d663d6d59994b7fa7390c9851966548.r2.dev/audio/haj-poetner/featured/shiraz%2F%D5%8D%D5%AB%D6%80%D5%B8%20%D5%B0%D5%A1%D5%B4%D5%A1%D6%80%20%D5%B4%D5%A1%D5%B0%20%D5%B9%D5%AF%D5%A1%2CFor%20Love%2C%20There%20Is%20No%20Death.mp3"
  },
  versions: {
    "go-hara|Սիրելով գնամ": "b5e360f88c88",
    "go-hara|Я уйду любя": "a4c22ad27185"
  },
  added: {
    "Աշնան Վալսը Պուրակում": "2026-10-04",
    "Ես չգիտեմ քե՞զ եմ սիրում": "2026-10-04"
  },
  order: {
    "imastun": ["andadar carav","Astghayin_Shghta_A","The Sun Cries Too(Արևն էլ է լաց լինում)","Vahan_Teryan_Gisher","B_Es_im_anush_Hayastani","ergi chapov","El_ban_chunem_Remix","taxicy vat margare e","Իմ Գեղեցկուհի ընկերուհիները","Իմ Գեղեցկուհի ընկերուհիները twist rock & roil","Իմ Գեղեցկուհի ընկերուհիներըroc&roil","im ser","inchi-hamar","inch_e_koracy_qarcr","lur-heraxos","lur uji simfonia","luse arzaganq","Luse_Hekiat_A","Lrutyan_unker","Lsir_vordis","Կատակ յարի երգ պար 4 լեզվով","Katak_Yari_Ergu","Կատակ Յարի Երգը","Katak_Yari_Ergu rem","haverji-erty","hogu-arzaganq","Մեղքի եզրին","On the Edge of Sin","Meghki_ezrin_Remix","Նախանձում եմ","shshnjatc","shshnjatc-noric","shepot","Ջրահարսեր Ремикс Ремикс_2","Ջրահարսեր Ремикс Ремикс_3","ser-anurji","sirelis","siro-kenacy","Поцелуй_ветра","Vahan_Teryan_MEGhAVOR_AChKERU","qo-jinj-hogin","A Song Away","IM JEALOUS OF THE MOSQUITO","Our Lovely Mermaids","Roses in a Sieve","The Eternal Thirst","На расстоянии песни","Песня шутка","pastayannaya jajda","Ревую к комару","Эй наши русалки","Ρόδα στο Κόσκινο","ვარდები საცერში","ჩვენი ქალთევზებო"],
    "silva-gulanyan": ["Akh_inch_anem_sirud_het","agh & dagy","Andzrevum_e","Mtnets_arants_kez_Duet","ari-khmenq","Ari_klini","Aryev_darnam","byur harvacneric","bjur u bjur angam","Galis_e_mi_pah_003","Garun_er_003","Garun e bajc zun e arel","gereckuhi","gjuk lusiny","gij","gij-qamin","Gisher_e_004","Gisherits_depi_luys_Silva_Gulanyan_005","gitem el inz ches spasum","Gitem_hogis_A","Gitem_ches_galu_B","gortrik-ankun","Դավաճան հայ","der-inz-voch-mek-chi-sirel-qo-pes","Դու իմ աշխարհն ես","Dran_Takotsu_003","ete asem","Եղբայր իմ անգին","Es_irakan_em_004","Es_sirum_em_ko_zhpitu_B","Es_kez_sirum_em","Erazankneri_aytsu_Part_Gisherva_002","erazi kyanq","erazi kyamq roc","Երանի գայիր(Just Like Before)","Erb_verkers_hanger_dardzri_Lyrics_by_Silva_Gulanyan_003","ergichy-dari","Erku_khent_hogi_Duet_Silva_Gulanyan_004","Թախծիս անունը","Թախծիս անունը_1","Թանկ հուշը","te karotum es","jpta hogis","Im_erazats_ashkharu_003","im-tsovagur","Իմ Քնքուշ Սևան","inch-em-anelu","inchu_es_ayskan_indz_otar_dardzel_004","lok cav u dard","luse hrashq","lrutian tchich","xararutun ber","xerdvac karot","xerdvac karot patasxan","խենթ խաղեր","xent siro qamin","xentern u lusiny","խենթի նման սիրահարվեցի","xind manuk","xortakvor nav","tsov-arev-achqer","Ծովի մեջ աչքերդ","Mer_Srterum_kanchu_004","Կարոտի խենթի","karotiali shurterin","kgam_sirelis","Kenatsd_khmem_B_Brinderò_per_Te","Kuratsats_achkin_luysu_003","Hay_aragil","Hayots_ashkarh_A","Havat_em_vozum_003","HERO_MOTIK_UNKERNERIS_003","Hetd_inch_e_katarvum","RokHetd_Inch_E_Katarvum_003","hiastapvac","hima","hogu giny","Kyanku_Hrashk_e_005","Dzig_tarineri_luys_003","Tchaxr e pargevum ","Chisht_zhamanakin_At_The_Right_Time","mek tari el ancav","mern zepur","Title_Mi_tanjir_hogis_Multilingual_Emotional_Duet_Lyrics_by_Silva_Gulanyan_002","Resta_nei_nostri_cuori","Nerir sirelis","nerqnapanak","Nrboren_Garnunk_003","ov em qez hamar","ughernery-lac-chen-linum","Che_chem_toghni_B","chem moracel","Ches_moranalu_003","Jaheli_nman_003","Tiezerk_Jinj_Lazur","ser da ardioq","ser eir xarum","Սիրել հենց հոգուն","Սիրել հենց հոգուն (1)","Sirir_indz_hogis_FRAM_Duet","melodia lubvi","siro cnundy","S_irum_em_kez_I_love_you","sirty xentacav","Srteri_kanchu_003","Ka_mi_ashkharh_vor_srtov_e_karutsvats","Tesilk_Silva_Gulanyan_Remix_Remix","Տիեզերական կինը","Տիեզերական կինը (Remastered)","Տիեզերական կինը roc","cav anbujeli","AKhor_vo_tsavits_tsnvats","Curt xavaric","Քեզ դուրս եմ արել","Kez_khenti_nman_siraharvetsi_Duet_Tango","qez karotelis","Քեզ կարոտելիս","qo cov achqeri kajcern em sirum","qo_drakhtum_002","Քո ժպիտները հավաքեմ","Ko_koghkin_vorish_em_003","Ko_hmayki_gerin","Kuyr_eghbayr_003","ov e kimy","frants_Harbel_em_vozum","Crazy Breeze of Love","I Gave My Sorrow The Name","Longing for You","Love Unseen","Love Unseen (1)","My Bright Dream","My Bright Dream (1)","My Endless Dream","My Only Light","My Precious Love","My Precious Love драгоценная любовь","Never a Stranger","Powerless Against Memories","The Illusion of Longing","The Night's Embrace","The Song of the Spring Breeze","The Sun Cries Too","The Woman as the Universe","You Are My World","Безумный Ветер Любви","Любить лишь душу","Любить лишь душу (1)","Мой светлый луч","Образы тоски","Перед памятью злой","Светлый полёт","Сокровенный причал","Тоска по мне","Тоскуя по тебе","ti moy kislarod","Ты мой мир","ti pridyosh komne","Я назвал свою печаль тоской","Խղճում եմ նրանց","Ուզում եմ նորից մանկանալ","Ոսկե աշուն","Աշնան Վալսը Պուրակում","Ես չգիտեմ քե՞զ եմ սիրում"],
    "go-hara": ["ajs xarum mian ujern e haxtum","Anund_Kin_e_004","Անունդ կին է ֆրի տանգո","Arajin_hambuyru","Arevamutits_araj","Bari_gisher","duet_Спокойной_ночи_Remix_Remix","spakojnoj nochi (kin)","Ginin_prprel_e","gisherajin","darnaham-ginin","daravor karnin","Դու եկար","Title_Es_arajva_pes_kez_karotum_em_Swiss_Pop_Ballad_Lyrics_by_Go_Hara_Remix_008","Եվ ինչ է սերը","Իմ հայելի","Im_poezian","la-fracise","pered rasvetom","kanchir-kgam","Հայաստան, մեր սուրբ տուն","HANDIPOMNERI_AYS_KhAChMEROKOM","Hervits_Grkum em","hognel em ujer kin lineluc","Hravirir_indz_parelu_tangon","menq linelu enq","MI_TOGh_INDz_MENAK","Mi_siro_patmutyun","urenineri lacor purakum","Չնոտագրված լռություն","POETIS","Սիրելով գնամ","Sirogisher_Go_Hara","cncir-users","Փխրուն Լաց","fracuzhenka","Armenia, Our Sacred Home","Fragile Cry Has Risen Like","Ill Leave Still Loving You","I'm tired of being strong","My Mirror True","You Came","Армения, наш святой дом","Во мне поднялся хрупкий плач","Зеркало моё","Ты пришёл","устала быть сильной","Я уйду любя"],
    "shakespeare-reimagined": ["Սոնետ 1","Սոնետ 2","Սոնետ 3","Սոնետ 4","Սոնետ 5","Սոնետ 6","Սոնետ 7","Սոնետ 8","Սոնետ 9","Սոնետ 10","Սոնետ 11","Սոնետ 12","Սոնետ  13","Սոնետ  14","Սոնետ  15","Սոնետ  16","Սոնետ  17","Սոնետ  18","Սոնետ  19","Սոնետ  20","Սոնետ  21","Սոնետ  22","Սոնետ  23","Սոնետ  24","Սոնետ  25","Սոնետ  26","Սոնետ  27","Սոնետ  28","Սոնետ  29","Սոնետ  30","Սոնետ  31","Սոնետ  32","Սոնետ  33","Սոնետ  34","Սոնետ  35","Սոնետ  36","Սոնետ  37","Սոնետ  38","Սոնետ  39","Սոնետ  40","Սոնետ  41","Սոնետ  42","Սոնետ  43","Սոնետ  44","Սոնետ  45","Սոնետ  46","Սոնետ  47","Սոնետ  48","Սոնետ  49","Սոնետ  50","Սոնետ  51","Սոնետ  52","Սոնետ  53","Սոնետ  54","Սոնետ  55","Սոնետ  56","Սոնետ  57","Սոնետ  58","Սոնետ  59","Սոնետ  60","Սոնետ  61","Սոնետ  62","Սոնետ  63","Սոնետ  64","Սոնետ  65","Սոնետ  66","Սոնետ  67","Սոնետ  68","Սոնետ  69","Սոնետ  70","Սոնետ  71","Սոնետ  72","Սոնետ  73","Սոնետ  74","Սոնետ  75","Սոնետ  76","Սոնետ  77","Սոնետ  78","Սոնետ  79","Սոնետ  80","Սոնետ  81","Սոնետ  82","Սոնետ  83","Սոնետ  84","Սոնետ  85","Սոնետ  86","Սոնետ  87","Սոնետ  88","Սոնետ  89","Սոնետ  90","Սոնետ  91","Սոնետ  92","Սոնետ  93","Սոնետ 94","Սոնետ  95","Սոնետ  96","Սոնետ  97","Սոնետ  98","Սոնետ  99","Սոնետ  100","Սոնետ  101","Սոնետ  102","Սոնետ  103","Սոնետ  104","Սոնետ  105","Սոնետ  106","Սոնետ  107","Սոնետ  108","Սոնետ  109","Սոնետ  110","Սոնետ  111","Սոնետ  112","Սոնետ  113","Սոնետ  114","Սոնետ  115","Սոնետ  116","Սոնետ  117","Սոնետ  118","Սոնետ  119","Սոնետ  120","Սոնետ  121","Սոնետ  122","Սոնետ  123","Սոնետ  124","Սոնետ  125","Սոնետ  126","Սոնետ  127","Սոնետ  128","Սոնետ  129","Սոնետ  130","Սոնետ  131","Սոնետ  132","Սոնետ  133","Սոնետ  134","Սոնետ  135","Սոնետ  136","Սոնետ  137","Սոնետ  138","Սոնետ  139","Սոնետ  140","Սոնետ  141","Սոնետ  142","Սոնետ  143","Սոնետ  144","Սոնետ  145","Սոնետ  146","Սոնետ  147","Սոնետ  148","Սոնետ  149","Սոնետ  150","Սոնետ  151","Սոնետ  152","Սոնետ  153","Սոնետ  154"],
    "haj-poetner": ["vahan-teryan/ananun ser","vahan-teryan/ashnan erg","vahan-teryan/Աշուն Է անձրև","vahan-teryan/es chgitem ur en tanum heravor","vahan-teryan/es sirum em qo meravor achqery xor","vahan-teryan/elegia","vahan-teryan/estonakan","vahan-teryan/im xarar erekon e hima","vahan-teryan/iriknajam","vahan-teryan/xarar gisherov du kgas inz mot","vahan-teryan/xosqery vchit en u xorunk","vahan-teryan/Կարոտ","vahan-teryan/hrajeshti gazel","vahan-teryan/hrashk argik","vahan-teryan/mtnshar","vahan-teryan/Մոռանալ","vahan-teryan/sentimental erg","vahan-teryan/sev gisher e noric u husher anhamar","vahan-teryan/qo achqeri dem im achqery kujr","vahan-teryan/Autumn and Rain  Աշուն Է անձրև","vahan-teryan/Golden Stars in Blue(Տխուր զրույց)","hamo-sahyan/axr es inchpes ver kenam gnam","hamo-sahyan/amen aravot","hamo-sahyan/Ամպ է Նորից","hamo-sahyan/anzrev","hamo-sahyan/anund talis","hamo-sahyan/arajin ser","hamo-sahyan/guce henc ajster","hamo-sahyan/du inz torel eir menak","hamo-sahyan/duq lavn eq mardiq","hamo-sahyan/es kuzei ","hamo-sahyan/es chem karogh chnershnchvel","hamo-sahyan/es chem karogh chnershnchvel roc","hamo-sahyan/es u du","hamo-sahyan/ev chimacanq te inchu","hamo-sahyan/torvochvoqi chkanchen","hamo-sahyan/tor vochvoqi chkanchen02roc","hamo-sahyan/torvochvoqi chkanchen roc","hamo-sahyan/inch anem mairik","hamo-sahyan/inch taqcnem","hamo-sahyan/inch arac mard em","hamo-sahyan/inchu hishecri","hamo-sahyan/covn er gisher er es ei u du","hamo-sahyan/ka mi tulutun","hamo-sahyan/kanch","hamo-sahyan/kgam","hamo-sahyan/hajastan aselis","hamo-sahyan/hajastan aselis roc","hamo-sahyan/hognel em","hamo-sahyan/horovely","hamo-sahyan/mer lezun","hamo-sahyan/mitegh ishxan u ter","hamo-sahyan/mijocners","hamo-sahyan/vochinch chi poxvi","hamo-sahyan/um hamar im ushqy gnac","hamo-sahyan/ches asi voch mi barov","hamo-sahyan/papy","hamo-sahyan/vshtacel em amen inchic","hamo-sahyan/tar inz jamanak","hamo-sahyan/tar inz jamanak roc","hamo-sahyan/Փնտրում ես դու","hamo-sahyan/qamu hamburic","hamo-sahyan/How Can I Just Leave","hamo-sahyan/I Will Come Anyway","hamo-sahyan/My First Love","hamo-sahyan/Our Language","hamo-sahyan/The Forest's Whisper","hamo-sahyan/The One in Vain","hamo-sahyan/The Thunderstorm","hamo-sahyan/vsio ravno pridu","hamo-sahyan/vsem kem ya bil","hamo-sahyan/dojd","hamo-sahyan/dojd roc","hamo-sahyan/kak je mne uyti","hamo-sahyan/mama","hamo-sahyan/moi sredstva moi zaboti","hamo-sahyan/moya neprojitaya jizn","hamo-sahyan/nash yazik","hamo-sahyan/pervaya lubov","hamo-sahyan/paceluy vetra","hamo-sahyan/proshay","hamo-sahyan/uznat menya ne tak prosto","hamo-sahyan/chto bilo to bilo","hamo-sahyan/ya xotel razdeliat","hamo-sahyan/Հայոց փշատենին","hamo-sahyan/Հայոց փշատենին ջազ","parujr-sevak/erku siro aranqum","parujr-sevak/erku siro aranqum roc","parujr-sevak/menq qich enq sakajn mez haj en asum","parujr-sevak/miangamic roc","parujr-sevak/miangamic tango","parujr-sevak/Նախանձում եմ","parujr-sevak/ՍԵՐՆ ԻՆՉ ԳՈՒՅՆ ՈՒՆԻ","parujr-sevak/What Color Is Love","parujr-sevak/Какого цвета любовь","avetik-isahakyan/Ախ կուզես լինիմ","aramayis-sahakyan/Ես կուզեի քո ճանապարհին","shiraz/Իմ պատանի սիրտս","silva-kaputikyan/Լուսինն ու Արևը","silva-kaputikyan/Ծուխը չերևա","silva-kaputikyan/Ոչ մեր սիրելն էր նման սիրելու","silva-kaputikyan/Սեր","silva-kaputikyan/Քեզ փնտրում եմ","silva-kaputikyan/The Moons Jealousy","silva-kaputikyan/Белая Луна","vahagn-davtyan/Սեր","hovhannes-tumanyan/Սիրում էի երբեմն քեզ","shiraz/Սիրո համար մահ չկա","shiraz/Հայոց լեզուն","shiraz/Սիրո հիասթափություն","shiraz/Իմ Սուրբ Հայրենիք","shiraz/Դու իմ միակ աստվածուհի","shiraz/Դու էլ ի՛մն ես"]
  }
};
